### ISSUE TITLE
Mono & Wine: SHA1 is an unsupported hash algorithm for RSA signing

### ISSUE THREAD

**Issue by t2946282** [vletoux/pingcastle#1]
Pingcastle doesn't work with Wine or Mono. Maybe this helps:

$ mono  PingCastle.exe
the license couldn't validate
=============================================================================
Program launched in interactive mode - press any key to terminate the program
=============================================================================

With command line debug:
mono PingCastle.exe --debug-license
Starting the license checking
License: _omitted_key_here_
.....
starting the license analysis
License info uncompressed
data Type = 1
EndTime
data Type = 3
CustomerNotice
data Type = 0
Signature
hashing license info
hashing done
loading rsa key
loading rsa key
verifying the signature
**License: exception SHA1 is an unsupported hash algorithm for RSA signing**the license check failed - please check that the .config file is in the same directory
the license couldn't validate
[Red]the license couldn't validate

$ gacutil -l | grep System.Security
System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by vletoux** [comment]
Does the replacement of the line 239 (https://github.com/vletoux/pingcastle/blob/master/License.cs#L239)
by using (SHA1Managed hashstring = new SHA1Managed()) fixe the problem?
(SHA1 is using CryptoAPI for security reason which may not be supported on wine)

**Comment by vletoux** [comment]
Ok
Mono expects null or the OID
Signature verification, expects null or an OID
https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Security.Cryptography/RSACryptoServiceProvider.cs#L375
SHA1 is not considered as an OID and raise an exception
https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Security.Cryptography/RSACryptoServiceProvider.cs#L317

**Comment by vletoux** [comment]
Problem is fixed by replacing "SHA1" by "1.3.14.3.2.26" in https://github.com/vletoux/pingcastle/blob/master/License.cs#L248
Will be fixed in the next version
