### ISSUE TITLE
License Version possible mismatch

### ISSUE THREAD

**Issue by red-erik** [vletoux/pingcastle#10]
Hello,
running the 2.7.0 version we receive
License valid for PingCastle 2.6.0.0 (Basic Edition)
don't know if it's by design, but I expected to read something like
License valid for PingCastle 2.7.0.0 (Basic Edition).

Regards.

Red.

**Comment by vletoux** [comment]
Hi,
There is no mismatch. Starting with 2.7, the license can be located in both .config file and the .exe itself.
It default to read the .config file which has not been updated (because inside the .exe)
I'll update the release (aka clean the license info in the .config file)

**Comment by vletoux** [comment]
Done
