### ISSUE TITLE
GPO access denied in v2.10.0.0 when passing creds with user argument

### ISSUE THREAD

**Issue by GiveMeTheBits** [vletoux/pingcastle#102]
Similar to issue #80 

passing Domain user creds logs GPO access Denied. Running across network, no trust to domain being queried.

Relevant error from --log

- Exception while generating GPO Data: The user name or password is incorrect.
-    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
-    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
-    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
-    at System.IO.DirectoryInfo.InternalGetDirectories(String searchPattern, SearchOption searchOption)
-    at PingCastle.ADWS.WindowsFileConnection.GetSubDirectories(String path) in c:\git\PingCastle\ADWS\WindowsFileConnection.cs:line 59
-    at PingCastle.Healthcheck.HealthcheckAnalyzer.ParseGPOFiles(ADWebService adws, ADDomainInfo domainInfo, Dictionary`2 GPOList) in c:\git\PingCastle\Healthcheck\HealthcheckAnalyzer.cs:line 1725

**Comment by vletoux** [comment]
be sure to type DOMAIN\USER or user@domain.com
The best is to use the runas command.

This is a known issue with impersonation using SMB

**Comment by GiveMeTheBits** [comment]
DOMAIN\USER was not working for any checks. user@domain.com only fails for GPO. RunAs will not work since there is no trust relationship to this domain. Any other options? I could consider a jumpbox in that domain, but we run it lean, more of a resource domain, and do not like to deploy more than we need to.

**Comment by vletoux** [comment]
You can profile runas on a non domain user with:
runas.exe /netonly /noprofile /user:DOMAIN\USER cmd.exe
netonly is important here

**Comment by GiveMeTheBits** [comment]
That appears to be the trick to doing it. Thank you, this worked.

**Comment by Houssem442** [comment]
Hello @GiveMeTheBits ,
Can you provide me your solution if possible ?
