### ISSUE TITLE
LAPS installation date is wrong

### ISSUE THREAD

**Issue by LoZio** [vletoux/pingcastle#103]
Using 2.10.0.
The report tells me that LAPS was installed 
LAPS installation date: 2017-08-23 11:32:49Z
But domain was created in Aug 2020, 13th. More that 3 years after, so the date is not correct.

**Comment by LoZio** [comment]
Added: the domain is part of a forest where it was indeed installed LAPS on 2017.
It would be more clear to say that LAPS was installed "in the forest" on xxyyzz.

**Comment by vletoux** [comment]
fix: added the phrase: "Please note that the LAPS schema is installed on the forest and as a consequence the installation date can be before the domain creation date."
