### ISSUE TITLE
Missing check: GPP autologon

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#11]
Hello,

PingCastle is able to detect the "GPP passwords" cases (encrypted "cpassword" field in some XML files of the sysvol).
But it doesn't seem to cover the "GPP autologon" cases. It's even easier since only "registry.xml" files are concerned and the login is in "DefaultUsername" and password in "DefaultPassword".

See this implementation example:
https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/Get-GPPAutologon.ps1

**Comment by vletoux** [comment]
Do you mean like it is done below ?
https://www.grouppolicy.biz/2010/10/how-to-use-group-policy-preference-enable-auto-logon/

**Comment by cnotin** [comment]
That's exactly this thing!

**Comment by cnotin** [comment]
By the way, it's not a request but only a kind suggestion :)

**Comment by vletoux** [comment]
Done for 2.8
![image](https://user-images.githubusercontent.com/10632326/65066108-0851cd80-d984-11e9-9a26-7b2cd9bb5b6f.png)

**Comment by cnotin** [comment]
That was fast! Thank you :)
