### ISSUE TITLE
Advised solution to Rule ID A-NoGPOLLMNR navigates to shady site

### ISSUE THREAD

**Issue by TwinkelToe** [vletoux/pingcastle#110]
Hello, 

The advised solution to Rule ID A-NoGPOLLMNR is to visit the link below. This page appears to have moved from:
https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.DNSClient::Turn_Off_Multicast
to:
https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.DNSClient::Turn_Off_Multicast

Translating the page gives some weird vibes.

--
line 2262:
https://raw.githubusercontent.com/vletoux/pingcastle/001131f863944d5829aa6b1506fe0f7bb8f62af6/Healthcheck/Rules/RuleDescription.resx

**Comment by vletoux** [comment]
I talk about it on twitter. The link has been changed for the next version
https://twitter.com/mysmartlogon/status/1461967820292509697?s=20

**Comment by TwinkelToe** [comment]
Owh my bad, thank you! :)
