### ISSUE TITLE
RuleID "P-ServiceDomainAdmin" is unclear or wrong

### ISSUE THREAD

**Issue by An-dir** [vletoux/pingcastle#112]
Hello 

i have noticed that the rule "P-ServiceDomainAdmin" seems to count wrong.
Example Title: 
> Presence of service accounts in the domain admin group (at least 2 accounts have a password which never expire): 3

Description: 
> The purpose is to check for "Service Accounts" in the "Domain Administrator" group

What your code does in my case:
`return domainadmins.NumberOfMemberPwdNeverExpires`

Where i tested:
Tested in 3 different domains with same results

What i expected:
"Title", "Description" and name of "RuleID" let me believe it should be about "Service Accounts" in "Domain-Admins" group. If service account is defined by "user has SPN" but i don't find users with SPN then the Description may be wrong. Also in "P-ServiceDomainAdmin" is says "The detail can be found in Admin Groups" but the col for "Nb Service accounts" is 0 for all 14 groups
I tried to find all users with PowerShell that might the three service accounts. Even that search that would returned 0 users.
`Get-ADUser -filter * -Properties servicePrincipalName,admincount | WHERE {$_.ServicePrincipalName -ne '' -and $_.admincount -eq "1" } | Select-Object DistinguishedName,ServicePrincipalName`

What i guess:
"P-ServiceDomainAdmin" has wrong description. It is not for service accounts. it is to keep Domain-Admins group clean and that includes admins to have changing passwords.

**Comment by vletoux** [comment]
you're right: this is one of the first pingcastle rules, maybe miss-labeled.
I'll review your comment to see how I can improve it.

**Comment by An-dir** [comment]
if you need some support or ideas let me know

**Comment by vletoux** [comment]
changed the description
![image](https://user-images.githubusercontent.com/10632326/147855014-f46fa6a3-77c6-4745-ad7a-146c27d13258.png)
