### ISSUE TITLE
Rule Exception ?

### ISSUE THREAD

**Issue by schoubi** [vletoux/pingcastle#114]
Hi,
First, thanks for this great tool which make AD Security a little bit easier :)

I saw in the A-LAPS-Not-Installed rule, the following : «If you mitigate the risk differently, you should add this rule as an exception, as the risk is covered»

I checked and double-checked `--help` and saw nothing about adding an exception...Read the doc neither helped me...

How should i do that ?

**Comment by vletoux** [comment]
Exception is part of the Pro / Enterprise version
sorry for that
(we need revenue to keep the software free for audits)

**Comment by schoubi** [comment]
ok no problem, maybe clarify somewhere that is part of pro-version ?
