### ISSUE TITLE
Check for completeness of network declaration

### ISSUE THREAD

**Issue by monamendes** [vletoux/pingcastle#115]
I have the error listed below on execution.
Can't find the fix, what code is executed? already tried to fix and this item returns
 Thanks

**Comment by vletoux** [comment]
there is no image nor logs.

br
v

**Comment by An-dir** [comment]
@monamendes do you have more details about your error?
Do mean you have hit the RuleID "S-DC-SubnetMissing"? Do you have the hint "The detail can be found in Domain controllers"? Are there any details in the section "Domain controllers"

You might have one or more DCs with one or multiple IP addresses where you do not have sites and services configured correctly.
if you cannot find it again maybe this powershell code might help you to identify the possibly inactive/removed adapter:
`Get-NetAdapter | Get-NetIPAddress -ErrorAction SilentlyContinue | ft InterfaceAlias,IPAddress`

be aware that one adapter can have multiple ip addresses in the advanced options.

If you prefer registry editor take a look there, but don't change anything unless you know what you are doing and have a current backup.
Regedit -> "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces"

**Comment by monamendes** [comment]
Thank you.
I managed to verify the origin and correct the score presented in Ping Castle.
Excellent tips. Thankful

**Comment by getsean** [comment]
I have nothing listed under "Subnets" in my AD Sites and Services. I took over this network been running fine for 10+ years. Should I go ahead and add our 1 network in there? Will this break anything if I do it after the fact? We also have an onsite OPEN-VPN server which hands out different IPs. Would it break that network if I do not include it?
