### ISSUE TITLE
PingCastle couldn't connect to the computer. The error was 0xc0020017

### ISSUE THREAD

**Issue by BigSap07** [vletoux/pingcastle#118]
I tried running a scan to see what remote control programs are installed on all our workstations but all our home setup pc's get denied or atleast they get this code as an error.
Workstations on site don't have this issue.

**Comment by vletoux** [comment]
it is working only on domain joined machine. It requires an authentication.

**Comment by vletoux** [comment]
Note: the error means "RPC_NT_SERVER_UNAVAILABLE" (aka firewall ?)
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
