### ISSUE TITLE
ad_scanner_zerologon_test.lab - Error 2: c0000022

### ISSUE THREAD

**Issue by ckrueger1979** [vletoux/pingcastle#119]
Hi Vincent,

I've tested PingCastle_2.10.1.0.Beta2 in the lab.
The zerologon test reported:
```
Computer	ISVulnerable
dc1.test.lab	Error 2: c0000022
```
Pingcastle was running on dc1 as DA

greetings
Carsten

**Comment by vletoux** [comment]
the error is access denied
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55
there is now security mechanism in place to block this

**Comment by ckruegerkpmg** [comment]
Thanks for the explanation.
I would none the less expect "True" or "False" not Error 2 ;-)
