### ISSUE TITLE
TGT delegation check on trust still with a bug?

### ISSUE THREAD

**Issue by phl0x1** [vletoux/pingcastle#12]
First of all thanks for that awesome tool you've created.

I'am a little confused by this Topic right now.

I do have Trusts which looks like the following:
TGTDelegation           : False
TrustAttributes         : 8 
WinServer2016 all patches installed.

With this info I would assume that this trust is not in a secure state.
Even PingCastle 2.7.1.0 told me that.

So I asked our Microsoft contact and he referred to your [social.msdn ](https://social.msdn.microsoft.com/Forums/en-US/385d30ad-acf5-4fe6-ab5d-1ab01bb0f37f/msadts-61679-trustattributes?forum=os_windowsprotocols)article with the line "by default this flag is clear, meaning the unconstrained delegation is disabled across forests".

Now I assume that my trusts are in a secure state because the attribute value is only set to 8.

So in my understanding PingCastle has still a bug. Am I wrong with this assumption?

**Comment by vletoux** [comment]
TrustAttribute as 8 is considered as a secure value.
I do not understand why this is a problem: in this case no rule is triggered and the TGT Delegation is indicated as disabled.

**Comment by phl0x1** [comment]
I downloaded the latest Version and run it again. In my case the rule is triggered and shown in the HTML Report as finding.
Thats the exact issue i want to report.

If you need further information of the trust configuration let me know.

**Comment by vletoux** [comment]
You were right, I put the 2.7.0.0. version into the 2.7.1.0 package.
Fixed
(a new 2.7.1.1 version)
