### ISSUE TITLE
Version 2.10.1.0.Beta3 reported as a virus/trojan

### ISSUE THREAD

**Issue by Need4Video** [vletoux/pingcastle#120]
Hello,

The beta 3 of PingCastle is reported as infected by a trojan. Could you please check why?

Please check the report available here: https://www.virustotal.com/gui/file/237b763022ff6b64f9fb9e3b6f05f9d4acd0c69f870c6795993c2e0b665742e6

Kind regards

**Comment by vletoux** [comment]
it is false positive, based on keyword (found on the explanation of the rules) or part of the code reused by other malware
I'll have to add AV mitigation by obfuscating the code ...
Hopefully the digital signature will allow a whitelist from the AV

**Comment by vletoux** [comment]
strange: the version I re-uploaded is not triggering the AV:
https://www.virustotal.com/gui/file/c9b52d03c66d54d6391c643b3559184b1425c84a372081ec2bfed07ebf6af275?nocache=1
Maybe I uploaded a wrong exe

**Comment by vletoux** [comment]
2.10.1.0 is considered safe
https://www.virustotal.com/gui/file/179be7c28eebe3aa04f75f9160945c56e0062708ae9d9055063ccf8d9fa0ea86?nocache=1

![image](https://user-images.githubusercontent.com/10632326/150177406-a1526b5d-b337-43d5-964d-39b2034f33ab.png)
