### ISSUE TITLE
Old version + end of support in README.md

### ISSUE THREAD

**Issue by Thijs0x57** [vletoux/pingcastle#123]
In the [Readme](https://github.com/vletoux/pingcastle/blob/master/README.md#introduction), the following lines are displayed:
```
  |:.      PingCastle (Version 2.5.2.0)
  |  #:.   Get Active Directory Security at 80% in 20% of the time
  # @@  >  End of support: 31/07/2020
  | @@@:
  : .#                                 Vincent LE TOUX (contact@pingcastle.com)
  .:                                                 https://www.pingcastle.com
```
I suggest updating the version in this example and the end of support, as to not confuse people.

**Comment by Thijs0x57** [comment]
I've created a pull request for this: [https://github.com/vletoux/pingcastle/pull/124](https://github.com/vletoux/pingcastle/pull/124)

**Comment by vletoux** [comment]
commited
