### ISSUE TITLE
regenerating report removes all nested tables from the report

### ISSUE THREAD

**Issue by hasamba** [vletoux/pingcastle#125]
reproduce steps:
1. generate healthcheck report
2. regenerate the report using the same xml pingcastle created (or any other)

problem: nested tables are missing, for example:
1st run:
![image](https://user-images.githubusercontent.com/7392290/150505574-488aa882-b911-41a4-beda-8d78ac26672c.png)
![image](https://user-images.githubusercontent.com/7392290/150505970-68e3bd26-89cd-4c49-98f1-f6b12156710a.png)

after regenerate, no link and cannot get into nested table:
![image](https://user-images.githubusercontent.com/7392290/150505629-628c5ba4-7fa8-47ed-b0f6-884d556416b2.png)
![image](https://user-images.githubusercontent.com/7392290/150506171-00ea9d76-886e-429a-bdaf-d7495b9e61be.png)

![image](https://user-images.githubusercontent.com/7392290/150505642-97df25bf-b6cb-4992-ad7b-22bd9b50fd94.png)

**Comment by vletoux** [comment]
This is on purpose:
all personal data are removed by default from the xml file
You have to add --level Full when generating the report

**Comment by hasamba** [comment]
after regenerating with level Full still doesn't get the nested tables

**Comment by vletoux** [comment]
This is working:
PingCastle --level Full => xml file => PingCastle regenerate

If you do:
PingCastle => xml file => PingCastle regenerate --level Full 
it won't work because the personal data are not in the xml file
