### ISSUE TITLE
GPO Data

### ISSUE THREAD

**Issue by hubkae** [vletoux/pingcastle#126]
Hi Vincent,

i consistently get an Error in the healthcheck-mode regarding GPO Data ("Exception while generating GPO Data: Username or Password wrong"). What am I doing wrong ?

Thanks !
Regards

**Comment by vletoux** [comment]
are you supplying a user name ?
Then, does it contains a \ or a @ in it ?

**Comment by hubkae** [comment]
Yes i am supplying a Username but it does not contain those Characters ... I´m doing the scan from a non domain-joined system.

**Comment by hubkae** [comment]
I have tried that too ... same Error

**Comment by vletoux** [comment]
most probably you need to audit it with a computer belonging to a domain
(that's because SYSVOL may be require to require SMB mutual authentication - mutual authentication = kerberos and not a computer non belonging to the daomin)

**Comment by ruppde** [comment]
@hubkae if the scanning machine isn't domain joined, you can start pingcastle from a cmd shell running in a domain context. start the shell with:

`runas /netonly /user:xyz@test.local cmd`

enter your password. in the shell that opens, if you don't get an error but output from `net view \\test.local`, it should be fine to run pingcastle.
