### ISSUE TITLE
XML Report - Wrong/missing data for HealthCheckGroupMemberData when member from child domain

### ISSUE THREAD

**Issue by An-dir** [vletoux/pingcastle#129]
Hello Vincent

just noticed that some data is not correct in the XML reports when you have multiple domains.
A user of childdomain was member of an admin group his parent/root domain! Thats already good to know for checking the security here, but you normally have data like "LastLogonTimestamp", "PwdLastSet", and "Created" in XML but in that case, these are missing. Your HTML Report seems to have a "dirty workaround"

Just to be sure we talk about the same data i show you how i could easily find the area in XML via PowerShell:
```
$healthCheckXML = ([xml](gc '.\ad_hc_customerdomain.tld.xml'))
$healthCheckXML.HealthcheckData.PrivilegedGroups.HealthCheckGroupData[1].members.HealthCheckGroupMemberData
```

Result looked like:
```
<HealthCheckGroupMemberData>
<Name>CorrectName</Name>
<IsExternal>true</IsExternal>
<DistinguishedName>CN=CorrectDN,OU=DomainAdmin,OU=Administration,DC=sub,DC=root,DC=com</DistinguishedName>
<IsEnabled>false</IsEnabled>
<IsActive>false</IsActive>
<IsLocked>false</IsLocked>
<DoesPwdNeverExpires>false</DoesPwdNeverExpires>
<CanBeDelegated>false</CanBeDelegated>
<LastLogonTimestamp>0001-01-01T00:00:00</LastLogonTimestamp>
<PwdLastSet>0001-01-01T00:00:00</PwdLastSet>
<SmartCardRequired>false</SmartCardRequired>
<IsService>false</IsService>
<Created>0001-01-01T00:00:00</Created>
<IsInProtectedUser>false</IsInProtectedUser>
</HealthCheckGroupMemberData>
```

There are multiple values that are not correctly filled in that case. Other Accounts wich are directly in "DC=root,DC=com" do not have that issue. i guess all data after DistinguishedName are not correct because you would need to get them from the external/trusted domain.

You have limitations like the PowerShell Commandlets so "get-aduser CorrectName -Properties pwdlastset,whencreated,lastlogon,lastlogontimestamp -Server sub.root.com" works from root, while "get-aduser CorrectName -Properties pwdlastset,whencreated,lastlogon,lastlogontimestamp" does not work from root.

Thats why you have "External" for all values of external Users in HTML Report.
Any chance to get a fix for XML like
- "External" in all values
- empty the values you could not get data
- skip the key entirely
- a description for how to (not) read the xml data.

Do you know more areas in XML wich are like that or the following ones that might make me fail to read the xml data correctly? May i have missed that in documentation?
"<LAPSInstalled>9999-12-31T23:59:59.9999999</LAPSInstalled>" when LAPS not installed (schema not extended).
"<PwdLastSet>1601-01-01T01:00:00+01:00</PwdLastSet>" = never
"<PwdLastSet>0001-01-01T00:00:00</PwdLastSet>" = external account
"<Created>0001-01-01T00:00:00</Created>" = external account
"<LastLogonTimestamp>0001-01-01T00:00:00</LastLogonTimestamp>" = never or external account

regards An-dir

**Comment by vletoux** [comment]
Won't fix
In short, when you have a domain trusting a child domain of a forest, this domain cannot connect to the root of the forest.
In addition to that, permissions may come from other domains (imagine an admin child domain).
This adds a complexity and the decision for the moment is not to connect to other domains to collect this info.
