### ISSUE TITLE
A-Guest Rule Bug?

### ISSUE THREAD

**Issue by PR3R00T** [vletoux/pingcastle#130]
Running the latest version of Ping Castle in a lab presents the rule A-Guest:

Rule ID:
A-Guest

Description:
The purpose is to ensure that the guest account of the domain is not enabled

Technical explanation:
The GUEST account is a special account whose SID is S-1-5-domain-501. It is used as a non nominative account to allow anyone to connect to the Active Directory.
Unless there is a justification about its activation, this represents a security issue because anybody can use this account to connect to any computer without any trace.

Advised solution:
You have to find the GUEST account and disable it.

Points:
15 points if present

However Looking at the lab AD the Guest account is disabled and it is the only user in the domain guest group.
![image](https://user-images.githubusercontent.com/50199640/154496515-fb3ff5c4-8f0a-483c-8dfe-220a572431b6.png)

Tried enabling and disabling again, still reports. Any ideas?

**Comment by vletoux** [comment]
can you show a screenshot of the guest user account with the following attributes ?
objectSID and userAccountControl

Thanks

**Comment by PR3R00T** [comment]
Hey @vletoux  please see below:
![image](https://user-images.githubusercontent.com/50199640/154928335-e6fe9526-8ac0-4f3f-bc2d-09727e690f36.png)
![image](https://user-images.githubusercontent.com/50199640/154928728-ed1cea92-a5d5-4061-80c2-b827db530fd2.png)
![image](https://user-images.githubusercontent.com/50199640/154928788-3d94c5c7-0147-4ea1-bc0a-53bebcbccd3d.png)

Apologies for the userAccountControl, Couldn't find a powershell command for it.

**Comment by vletoux** [comment]
This is very strange because the code associated to the check shouldn't be trigger here:
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/HealthcheckAnalyzer.cs#L460-L466

Are you running the code in a different account that could explain why is not seeing the same properties ?

**Comment by PR3R00T** [comment]
Hey @vletoux 
So running PingCastle 2.10.1.0 as a created account with domain admins group privileges. 
interactive mode - healthcheck -default Domain (my case AC.LOCAL) through CMD.
...
And I've just seen a difference, so when I run the same exe (copied from the created account's desktop) and run while logged in as the default Administrator account I do not get the guest account in the report. 
Below is the groups of the created account used to run the script originally.
![image](https://user-images.githubusercontent.com/50199640/154949931-aa1c99fe-29c7-4aec-ab78-5fe35810f91d.png)

**Comment by vletoux** [comment]
I think you have a permission issue that shows different results based on the user you are running 
You’d better run adexplorer with these different identities to find the root cause

**Comment by Nioubi24** [comment]
Hi,
I've got the same issue on this rule : the account (S-1-5-21-***-501) is disabled : userAccountControl = 546 NORMAL_ACCOUNT+PASSWD_NOTREQD+ACCOUNTDISABLE , but the rule triggers... ?
Regards

**Comment by vletoux** [comment]
This is because the permission hide the useraccountcontrol attribute (set it to zero, then zero  = ACCOUNT DISABLED)
