### ISSUE TITLE
AD query failed - An exception occured while querying the Active Directory

### ISSUE THREAD

**Issue by raheelb** [vletoux/pingcastle#135]
Having issue running PingcCastle -  V 2.10.1.1

The AD query failed. Using the alternative protocol (LDAPConnection)
An exception occured while querying the Active Directory
Exception: There is no such object on the server.
(0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match

Aslo ran with --protocol LDAPOnly, still the same error

![Error](https://user-images.githubusercontent.com/96928791/163474501-f34ba44c-261c-488c-a956-b05066f4dff3.png)

Log File

[Log.txt](https://github.com/vletoux/pingcastle/files/8492233/Log.txt)

**Comment by vletoux** [comment]
can you contact support@pingcastle.com ?

**Comment by raheelb** [comment]
Issue was resolved with test version 2.11.0
