### ISSUE TITLE
Rule P-DelegationDCt2a4d: incorrect check

### ISSUE THREAD

**Issue by SAERXCIT** [vletoux/pingcastle#137]
Hi!

I think rule `P-DelegationDCt2a4d` ("Check if all DC have no constrained delegation with protocol transition") is performed incorrectly.

https://github.com/vletoux/pingcastle/blob/319b35ebe0e5a71083d8761731b5a1091ffd3d0d/Graph/Export/ExportDataFromActiveDirectoryLive.cs#L166-L169

The code checks if the account's `UserAccountControl` attribute has the flag `0x80000` (`TRUSTED_FOR_DELEGATION`). However, this flag corresponds to Unconstrained Delegation:

![Unconstrained](https://user-images.githubusercontent.com/78735647/169561863-608e6e68-b99f-4ca9-aca3-758b9df4eb10.png)

Protocol transition is instead set with the flag `0x1000000` (`TRUSTED_TO_AUTH_FOR_DELEGATION`):

![ConstrainedwithProtocolTransition](https://user-images.githubusercontent.com/78735647/169562338-875f5a2d-a4e4-4e0c-9cbe-dd3e446088bc.png)

(And for reference, simple Constrained Delegation without protocol transition does not set any specific UAC flag):

![Screenshot from 2022-05-20 17-09-24](https://user-images.githubusercontent.com/78735647/169562694-63f70b72-90cf-4dbd-a6a0-a7db1dfe936d.png)

Admittedly the MS documentation on these flags is very confusing (https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/useraccountcontrol-manipulate-account-properties).

Cheers!

**Comment by vletoux** [comment]
ok, well spotted !
Fixed for the next version, thanks
