### ISSUE TITLE
Cosmétique de pingcastle dans le terminal

### ISSUE THREAD

**Issue by hcx35** [vletoux/pingcastle#138]
<pre>
 Propositions totalement inutiles, donc indispensables ;-)
 (A basculer en chasse fixe pour y voir qqchose) :

Le rendu dans Github est KO: le fichier ici: https://filetransfer.io/manage-package/XpUA5UmJ

 |:. PingCastle (Version 2.10.1.1 10/03/2022 13:05:42)
 
 |:.      PingCastle (Version 2.10.1.1     10/03/2022 13:05:42)
 |  #:.   Get Active Directory Security at 80% in 20% of the time
 # @@  >  End of support: 31/07/2023
 | @@@:
 : .#                                 Vincent LE TOUX (contact@pingcastle.com)
   .:       twitter: @mysmartlogon                    https://www.pingcastle.com
 
 ---------------------------
                 
  \͞―─̵O̵_       PingCastle (Version 2.10.1.1 10/03/2022 13:05:42)
   \  / \ ᷈͡¨>   Get Active Directory Security at 80% in 20% of the time
    \/   \ ͵’    End of support: 31/07/2023
     O¨--˗Ǿ                                                     
      \ ͵'       Vincent LE TOUX (contact@pingcastle.com)
       ⱱ         twitter: @mysmartlogon       https://www.pingcastle.com
                 
 
 ---------------------------
 
                  ___  _  _  _  ___    ___   _   ___ _____ _    ___  
  \͞―─̵O̵_       | _ || || \| |/ __|  / __| / \ / __|_   _| |  | __| 
   \  / \ ᷈͡¨>   |  _/| || .` | (_ | | (__ /   \\__ \ | | | |__| _|  
    \/   \ ͵’    |_|  |_||_|\_|\___|  \___|_____|___/ |_| |____|___| 
     O¨--˗Ǿ                                                          
      \ ͵'       Version 2.10.1.1 10/03/2022 13:05:42
       ⱱ         Get Active Directory Security at 80% in 20% of the time
                 End of support: 31/07/2023
 
                 Vincent LE TOUX (contact@pingcastle.com)
                 twitter: @mysmartlogon       https://www.pingcastle.com
 
 ---------------------------
 
 ┌───────────────────────────────────────────────────────────────────────────┐
 │                  ___  _  _  _  ___    ___   _   ___ _____ _    ___        │
 │  \͞―─̵O̵_       | _ || || \| |/ __|  / __| / \ / __|_   _| |  | __|       │
 │   \  / \ ᷈͡¨>   |  _/| || .` | (_ | | (__ /   \\__ \ | | | |__| _|        │
 │    \/   \ ͵’    |_|  |_||_|\_|\___|  \___|_____|___/ |_| |____|___|       │
 │     O¨--˗Ǿ                                                                │
 │      \ ͵'       Version 2.10.1.1 10/03/2022 13:05:42                      │
 │       ⱱ         Get Active Directory Security at 80% in 20% of the time   │
 │                 End of support: 31/07/2023                                │
 │                                                                           │
 │                 Vincent LE TOUX (contact@pingcastle.com)                  │
 │                 twitter: @mysmartlogon       https://www.pingcastle.com   │
 └───────────────────────────────────────────────────────────────────────────┘
</pre>

**Comment by hcx35** [comment]
``
|:.      PingCastle (Version 2.10.1.1     10/03/2022 13:05:42)
|  #:.   Get Active Directory Security at 80% in 20% of the time
# @@  >  End of support: 31/07/2023
| @@@:
: .#                                 Vincent LE TOUX (contact@pingcastle.com)
  .:       twitter: @mysmartlogon                    https://www.pingcastle.com

---------------------------
                
 \͞―─̵O̵_       PingCastle (Version 2.10.1.1 10/03/2022 13:05:42)
  \  / \ ᷈͡¨>   Get Active Directory Security at 80% in 20% of the time
   \/   \ ͵’    End of support: 31/07/2023
    O¨--˗Ǿ                                                     
     \ ͵'       Vincent LE TOUX (contact@pingcastle.com)
      ⱱ         twitter: @mysmartlogon       https://www.pingcastle.com
                

---------------------------

                 ___  _  _  _  ___    ___   _   ___ _____ _    ___  
 \͞―─̵O̵_       | _ || || \| |/ __|  / __| / \ / __|_   _| |  | __| 
  \  / \ ᷈͡¨>   |  _/| || .` | (_ | | (__ /   \\__ \ | | | |__| _|  
   \/   \ ͵’    |_|  |_||_|\_|\___|  \___|_____|___/ |_| |____|___| 
    O¨--˗Ǿ                                                          
     \ ͵'       Version 2.10.1.1 10/03/2022 13:05:42
      ⱱ         Get Active Directory Security at 80% in 20% of the time
                End of support: 31/07/2023

                Vincent LE TOUX (contact@pingcastle.com)
                twitter: @mysmartlogon       https://www.pingcastle.com

---------------------------

┌───────────────────────────────────────────────────────────────────────────┐
│                  ___  _  _  _  ___    ___   _   ___ _____ _    ___        │
│  \͞―─̵O̵_       | _ || || \| |/ __|  / __| / \ / __|_   _| |  | __|       │
│   \  / \ ᷈͡¨>   |  _/| || .` | (_ | | (__ /   \\__ \ | | | |__| _|        │
│    \/   \ ͵’    |_|  |_||_|\_|\___|  \___|_____|___/ |_| |____|___|       │
│     O¨--˗Ǿ                                                                │
│      \ ͵'       Version 2.10.1.1 10/03/2022 13:05:42                      │
│       ⱱ         Get Active Directory Security at 80% in 20% of the time   │
│                 End of support: 31/07/2023                                │
│                                                                           │
│                 Vincent LE TOUX (contact@pingcastle.com)                  │
│                 twitter: @mysmartlogon       https://www.pingcastle.com   │
└───────────────────────────────────────────────────────────────────────────┘

**Comment by vletoux** [comment]
Merci je vais regarder ca

**Comment by vletoux** [comment]
Le lien n'est plus valide.

Le code proposé donne cela:
![image](https://user-images.githubusercontent.com/10632326/172013545-5a68b116-e610-4756-87e8-a98992b3503f.png)

C'est à dire que la console interdit certains caractères unicode et qu'il faut se limiter aux caractères "habituels"
Voici ce que ça donne si on retravaille le logo:
![image](https://user-images.githubusercontent.com/10632326/172013793-1860a9fe-0f7f-46b7-9c28-956dde636449.png)

le code c# associé est:
```
            ConsoleMenu.Header = @"  \==--O___      PingCastle (Version " + version.ToString(4) + @"     " + ConsoleMenu.GetBuildDateTime(Assembly.GetExecutingAssembly()) + @")
   \  / \  """">   Get Active Directory Security at 80% in 20% of the time
    \/   \ ,’    " + (license.EndTime < DateTime.MaxValue ? "End of support: " + license.EndTime.ToShortDateString() : "") + @"
     O¨---O                                                     
      \ ,'       Vincent LE TOUX (contact@pingcastle.com)
       v         twitter: @mysmartlogon       https://www.pingcastle.com";
```

Et le code ascii imprimé sur la console:
```
  \==--O___      PingCastle (Version 2.11.0.0     04/06/2022 17:55:37)
   \  / \  "">   Get Active Directory Security at 80% in 20% of the time
    \/   \ ,'    End of support: 28/07/2022
     O¨---O
      \ ,'       Vincent LE TOUX (contact@pingcastle.com)
       v         twitter: @mysmartlogon       https://www.pingcastle.com
```

J'ai tenu compte des remarques et modifié le logo en m'inspirant des changements proposés.
