### ISSUE TITLE
Suggestion pour la règle S-PwdNeverExpires

### ISSUE THREAD

**Issue by Y0rf** [vletoux/pingcastle#139]
La règle S-PwdNeverExpires comptabilisent les comptes « techniques » HealthmailboxXXX, créés par Exchange pour le monitoring des mailbox. Ces comptes faussent un peu l’indicateur en noyant les comptes de services créés manuellement et sur lesquels il faut vraiment agir.
Peut-on suggérer de scinder cette règle en 2 ?
- La règle S-PwdNeverExpires *sans* les comptes healthmailboxXXX
- Une ‘informative rule’ *uniquement* pour les comptes HealthmailboxXXX (avec éventuellement leur nettoyage régulier proposé).

https://docs.microsoft.com/en-us/answers/questions/604041/healthmailbox-user-accounts.html
https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-2013-2016-monitoring-mailboxes/ba-p/611004

Merci pour cet outil précieux !

**Comment by vletoux** [comment]
C'est déjà exclus dans la prochaine version si le mot de passe est changé dans les derniers 40 jours
