### ISSUE TITLE
P-OperatorsEmpty only 2 of 5 operators groups

### ISSUE THREAD

**Issue by An-dir** [vletoux/pingcastle#141]
Hello,

I was wondering if the healthcheck rule P-OperatorsEmpty is incomplete. You show 5 "Operators" groups in HTML report in the admin groups part below all findings. But in the finding P-OperatorsEmpty you mention and list only 2 of them, but a "..." makes me believe you want to show more. 

Report HTML:
Operator groups (account operators, server operators, **...**) can take indirect control

The relevant line of code is this:
https://github.com/vletoux/pingcastle/blob/319b35ebe0e5a71083d8761731b5a1091ffd3d0d/Healthcheck/Rules/HeatlcheckRulePrivilegedOperatorsEmpty.cs#L23

**Comment by vletoux** [comment]
this is on purpose.
The other groups (backup operators, print operators, ...) are the subject of different rules
