### ISSUE TITLE
Erro matriz

### ISSUE THREAD

**Issue by Rodrigocg** [vletoux/pingcastle#143]
![image](https://user-images.githubusercontent.com/5504567/186155299-7c7a42be-943a-4941-8d21-4a804b2b5cd2.png)

![image](https://user-images.githubusercontent.com/5504567/186155220-d377a402-a3be-455b-b107-650b6cae2278.png)

**Comment by vletoux** [comment]
What version are you using ?
Are you able to reproduce it ?
Can you attached the trace log ?

your bug report doesn’t include much detail and as a consequence it will be difficult to answer.

also from what I understand from the trace log you have a privilege group that contains a lot of users and your domain seems to be larger than the memory capacity of your computer…

**Comment by Rodrigocg** [comment]
What version are you using ? 
2.11.0.0
Are you able to reproduce it ?
No
Can you attached the trace log ?
No, sorry. Is there a way to increase the verbosity of the error log?

your bug report doesn’t include much detail and as a consequence it will be difficult to answer.
Okay, despite the error, the report is generated, but it must be incomplete.

also from what I understand from the trace log you have a privilege group that contains a lot of users and your domain seems to be larger than the memory capacity of your computer…
I don't think it's the memory.

**Comment by Rodrigocg** [comment]
The error persists in previous versions

**Comment by vletoux** [comment]
In the advanced menu there is a log option.
It enables you to create a trace.log file in the same directory at each run.
