### ISSUE TITLE
[Feature request] Excel report summary and/or small changes to XML reports

### ISSUE THREAD

**Issue by semangard** [vletoux/pingcastle#145]
Hello,

a) HTML reports are great but it could be interesting also to generate an Excel summary report for all the domains analyzed because for some companies the action plan is managed by Excel sheets.

Example of Excel report (cf. also attachment):
![image](https://user-images.githubusercontent.com/57065741/192971658-2ee773d5-22b6-4157-99ad-8d52aa149f6c.png)

[SummaryReport_Example.xlsx](https://github.com/vletoux/pingcastle/files/9672326/SummaryReport_Example.xlsx)

b) If it is not possible to generate this kind of Excel report,
Then would it be possible to slightly review the XML reports:
- add the unique ID to each rule, this ID would never change which is not always the case of issues' label
- add the level (1-5) of each issue
- be sure that all the issues found are listed by <RiskRules>

Thanks and Regards

**Comment by vletoux** [comment]
a) Excel exports are targeted for paid version and won't be added to free ones
(technically this report is present only on the enterprise edition)

b) the id of the rule is already present.
Won't include maturity level because it's part of paid package

**Comment by semangard** [comment]
Ok.

a) Would it possible to add Excel reports to the auditor license also (even if required with an extra optional cost) ?

**Comment by vletoux** [comment]
it already exists for the Enterprise edition (with comments with rule detail) and there is no reason to implement it a second time
![image](https://user-images.githubusercontent.com/10632326/192979162-cc98379b-bc83-4eae-84ee-d576db82e7ec.png)
