### ISSUE TITLE
T-AlgsAES - La règle se déclenche même sur des trust de type External 

### ISSUE THREAD

**Issue by julien220885** [vletoux/pingcastle#149]
Bonjour,

Lors de la génération de l'audit de notre forêt la règle T-AlgsAES s'est déclenchée sur un de nos trusts.
Après vérification, ce trust est de type EXTERNAL, non-transitive et de sens OUTBOUND. Nous n'avons donc pas la possibilité de supprimer le protocol RC4 dans l'attribut msDS-SupportedEncryptionTypes puisque ce dernier n'est pas présent.

Si mon analyse est correcte, serai t’il possible dans une prochaine version de ne pas vérifier les trust de ce type ?

Merci.
Julien

**Comment by vletoux** [comment]
je vous invite à vérifier que les attributs non vides sont bien affichés ce qui est le cas par défaut avec adsiedit

**Comment by julien220885** [comment]
Effectivement !
Les attributs vides étaient masqués. Désolé pour cette mauvaise analyse...
Bonne soirée et merci pour ce retour rapide.
