### ISSUE TITLE
A-LAPS-Not-Installed warning but LAPS is installed

### ISSUE THREAD

**Issue by fredericpetit02** [vletoux/pingcastle#150]
Hi, i have the warning but LAPS is installed by Chocolatey ( https://community.chocolatey.org/packages/laps ) with `--params='"/ALL"'` :

> Installs the AdmPwd GPO Extension and all Management Tools (Fat client UI, PowerShell module, and GPO Editor templates)

warning detail :
> LAPS installation date: Never

**Comment by vletoux** [comment]
What is the result of the ldap request (name=ms-*-AdmPwd) when you search under the schema partition ?
(use adexplorer to do it)
To be installed laps require a schema extension and pingcastle checks for it
