### ISSUE TITLE
S-DC-SubnetMissing

### ISSUE THREAD

**Issue by dnsss90** [vletoux/pingcastle#151]
The rule S-DC-SubnetMissing is warning for missing declared subnets even in single site topology ADs causing unnecessary noise.

**Comment by vletoux** [comment]
You are missing the big picture 
When you have multiple domains you want to consolidate having the ip range defined help building the map (checkout the Hilbert report)
That’s why we require it even for single site

**Comment by dnsss90** [comment]
Sorry, I meant in a single site and single domain topology it’s not necessary (only adds complexity).

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: vletoux ***@***.***>
Skickat: Wednesday, October 26, 2022 7:09:52 PM
Till: vletoux/pingcastle ***@***.***>
Kopia: dnsss90 ***@***.***>; Author ***@***.***>
Ämne: Re: [vletoux/pingcastle] S-DC-SubnetMissing (Issue #151)


You are missing the big picture
When you have multiple domains you want to consolidate having the ip range defined help building the map (checkout the Hilbert report)
That’s why we require it even for single site
