### ISSUE TITLE
SmartCard password age check number of days mismatch

### ISSUE THREAD

**Issue by csandfeld** [vletoux/pingcastle#154]
For the SmartCard check I have noticed a mismatch between the password age in days (40) shown in the report, and the age in days (90) in the rule description and the actual health check.

**Report**
https://github.com/vletoux/pingcastle/blob/ef2c71818d0f5b521d2e0cfec41fc686528d453b/Report/ReportHealthCheckSingle.cs#L3307-L3324

**Rule Description**
https://github.com/vletoux/pingcastle/blob/d2b15aa3e672371d98c769b234da87689456c4ed/Healthcheck/Rules/RuleDescription.resx#L1180

**Health check**
https://github.com/vletoux/pingcastle/blob/cfb4a0e26fa9a9aa0f006053307cdec322845287/Healthcheck/HealthcheckAnalyzer.cs#L4374

**Comment by vletoux** [comment]
Indeed.
I'll fix the reference to 40 days which was later changed by 90 days in the next version

**Comment by csandfeld** [comment]
Thanks 👍
