### ISSUE TITLE
3.0 LAN MAN

### ISSUE THREAD

**Issue by stondino00** [vletoux/pingcastle#159]
I don't believe the 3.0 version is correctly searching for LAN MAN settings.

The below appears on 3.0 when 2.11 doesn't show this as a finding.  Both sections are identical when you scroll down to security settings.

![image](https://user-images.githubusercontent.com/54154986/217639589-ece87a87-a656-4dd8-95ee-fd8aefe7a000.png)

**Comment by mpgn** [comment]
Same behavior, while a gpo to force ntlmv2 on the DC is set.

**Comment by vletoux** [comment]
Yes, there is a bug that I fixed.
Does the version [https://www.dropbox.com/t/g3w0GdkCESgpBJgi](https://www.dropbox.com/l/AAAOzDb54W6WAYQiigYEVYECKN_zrKgBlVE) fixed the bug ?

**Comment by stondino00** [comment]
Yes sir!  That appears to have done it.  Thanks so much!
