### ISSUE TITLE
3.0 Kerberos Armoring No Info In Security Settings Section

### ISSUE THREAD

**Issue by stondino00** [vletoux/pingcastle#160]
Seeing this new section appear with 3.0.  When you click on the link, nothing in the section gives information about these findings it appears.

![image](https://user-images.githubusercontent.com/54154986/217905466-e8c6ed97-87a5-497b-a540-5fe28482abbd.png)

**Comment by vletoux** [comment]
it was mean "if activated, the detail can be found xxx"
in this case, it is not activated, thus nothing can be displayed

Improved wording for next release
