### ISSUE TITLE
Feature request: LAPS usage

### ISSUE THREAD

**Issue by thaneye** [vletoux/pingcastle#164]
Provide metrics on how many computers use the LAPS by enumerating the attributes:
ms-Mcs-AdmPwd
ms-Mcs-AdmPwdExpirationTime

**Comment by vletoux** [comment]
In 3.0.0.3

**Comment by mpgn** [comment]
Hello @vletoux the new Windows LAPS use `msLAPS-Password` or `msLAPS-EncryptedPassword` not `ms-Mcs-AdmPwd` anymore

**Comment by jamesaepp** [comment]
@mpgn please upvote/comment in https://github.com/vletoux/pingcastle/issues/179
