### ISSUE TITLE
A-HardenedPaths: wrong statement about default configuration

### ISSUE THREAD

**Issue by ruliane** [vletoux/pingcastle#165]
As of Pingcastle release 3.0.0, rule A-HardenedPaths usually appears on reports. The technical explanation states that 
> By default if this policy is empty, if will enforce Integrity and Mutual Authentication on the SYSVOL or NETLOGON shares.

However, as far as I understand after a deeper look at the related documentation, the default configuration **does not** enforce any security mechanism.
I suggest removing the aforementioned sentence.

Side note: changelog has been mentioning A-HardenedPaths since 2.10.1.0. Don't know why this rule doesn't appear before 3.0.0.

**Comment by vletoux** [comment]
Indeed.

I change it to: "By default if this policy is empty, if will NOT enforce Integrity and Mutual Authentication on the SYSVOL or NETLOGON shares."

**Comment by ruliane** [comment]
This has not changed on 3.2.0.1 nor 3.3.0.0Beta1.
