### ISSUE TITLE
Option to set report location

### ISSUE THREAD

**Issue by sjwk** [vletoux/pingcastle#167]
Is there an option (I couldn't find one) to specify the location to save the report to?  It just seems to save to current directory which is fine when run interactively, but complicates things if you want to run it from a scheduled task and saving reports to a UNC path. (for instance).

**Comment by vletoux** [comment]
PingCastle saves to the current directory.
You can change the current directory (ex: in a link or in a scheduled task)
Or you can run PingCastle using the full path.
Ex:
```
c:\> cd output
c:\output\> c:\directory\PingCastle.exe --interactive

```

**Comment by sjwk** [comment]
Windows doesn't let you specify a UNC path as the run from location on a scheduled task and can't guarantee a drive mapping exists - currently I've written a batch wrapper to map/unmap drives etc - was just thinking that a parameter to say where to save it would be easier but no worries!
Thanks for the speedy answer.
