### ISSUE TITLE
AES Trust check

### ISSUE THREAD

**Issue by mgirardi23** [vletoux/pingcastle#169]
A false positive is identify when forest trust are analyzed
When you enable a trust (es: one direction only) on the outgoing you cannot enable AES and even if you enabled AES on the incoming trsut pingcastle identify it ass an issue
In Ping Castle section: Healthcheck analysis - trusts - trusts rule details - AES is not enabled on all trusts

**Comment by vletoux** [comment]
We are aware of this issue and it has already been fixed for the next release
