### ISSUE TITLE
"Misleading" numbers of DC reported because of object "AzureADKerberos"

### ISSUE THREAD

**Issue by Lennyroquai** [vletoux/pingcastle#178]
Hello,

As i've scratched my head on this one ;)

For info : Pingcastle was reporting a misleading number of DCs in my environment, with 1 "ghost DC"

This was caused by the object "AzureADKerberos" which is considered as a RODC (test is "PrimaryGroupID -eq 521") but not displayed by the classic powershell commands or withing the usual MMCs.
The object could be also in another OU than the usual "Domain Controllers" one

I was believing in something like a rogue entry somewhere referring to a decommissionned DCs in my environment

**Comment by vletoux** [comment]
This should be fixed.
Reopen if not please.
