### ISSUE TITLE
Mispelling in Healthcheck/Rules/RuleDescription.resx 

### ISSUE THREAD

**Issue by skwd** [vletoux/pingcastle#18]
Engine version: 2.7.1.1 

In Healthcheck/Rules/RuleDescription.resx line 392 

The LDAP search texte sould have be : (sAMAccount**Name**=*$$$) instead of (sAMAccount**Nmae**=*$$$)

First time reporting issue. Let me know if you need more information. 

Great Tool by the Way 👍

**Comment by vletoux** [comment]
well spoted.

Fixed in the source code for the next version.
