### ISSUE TITLE
What's new/changed/fixed in PC 3.0.0.4?

### ISSUE THREAD

**Issue by DannyPans** [vletoux/pingcastle#183]
Please update changelog.txt
Thank you
Danny

**Comment by An-dir** [comment]
Changelog in source has been updated, but not in the release.

```
3.0.0.4
* fix channel binding issue (if server was configured with only TLS1.2 and client was not configured for TLS1.2 in the default algorithm it was not tested)
* fix integrity bug for paid subscriptions
```
You can find the latest changelog here:
https://github.com/vletoux/pingcastle/blob/master/changelog.txt

**Comment by An-dir** [comment]
@DannyPans You might close this issue on your own (I can't do it). New Release with releasenotes is on its way and currently in Beta1

**Comment by DannyPans** [comment]
Closed
