### ISSUE TITLE
ACL scanner

### ISSUE THREAD

**Issue by thaneye** [vletoux/pingcastle#187]
Can you enable a default execution of aclcheck scanner or at least allow the users to be added as rguments? 

Currently if you execute  `PingCastle.exe --scanner aclcheck` an extra step needed to include users.

**Comment by An-dir** [comment]
I would like to suggest to add the parameter `--scmode-file` (like smb scanner) to the code that may contain a separated list of names or SIDs one per line. If `--scmode-default` with an empty value is given it could switch to default (everyone, ...). Both options should skip interactive mode.

**Comment by clamoune** [comment]
The other way to do it, is to create a txt file with a carriage return save it. 
Launch the command : pingcastle --servername %server_name% --scanner aclcheck < txt_file

**Comment by vletoux** [comment]
the alternative is to run:
`echo. | pingcastle --server %server_name% --scanner aclcheck`
Important: no space between echo and dot
