### ISSUE TITLE
Improve list of indirect members

### ISSUE THREAD

**Issue by ruppde** [vletoux/pingcastle#188]
hello Vincent,

the lists of indirect members in the control path analysis would be more useful, if they didn't only show the firstname, lastname and SID of the user, but also the samAccountName. (or skip the firstname, lastname because that's also shown in the last column "path"?)

regards
arnim

**Comment by An-dir** [comment]
You mean "Indirect Control" / "Indirect Member" lists? In the newest version there are the following columns


Name | Distance | Last authorized object | Path
-- | -- | -- | --

I Guess that is enough and good so.

**Comment by ruppde** [comment]
The problem with first and last name is that it's not unique. There are multiple John Smiths in a big company. And the SID isn't useful in many tools. But the samAccountname is unique and eaten by many tools.

**Comment by vletoux** [comment]
you need to open the complete path and look at the object.
Designing a UI with limited size and ergonomy is not easy ;-(
