### ISSUE TITLE
Fix using domain FQDN for connection when NTLM is blocked

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#19]
It's not possible to use the domain FQDN (e.g. `corp.domain.com`) to establish a connection to a DC in environments where NTLM authentication is blocked. PingCastle uses the domain FQDN as the default unless a DC has been explicitly specified. The problem appears to be two-fold:

**ADWS connection**
PingCastle first attempts to connect to a DC via ADWS using Negotiate authentication. Kerberos authentication fails as the provided SPN is the IP address of the target DC (e.g. `host/1.2.3.4`). I'm guessing this is determined by a (probably cached) `A` record DNS query for the domain FQDN. SPNs for the IP address(es) of DCs are not registered by default and so the DC's computer account is not mapped to the SPN. NTLM authentication is subsequently tried but fails as expected. The process appears to repeat for each DC in the domain, but I've only tested this against a domain with two DCs so there may be a maximum number of attempts I haven't witnessed.

It's possible this could be handled by performing a reverse DNS query for the IP address being connected to and using the result to construct the SPN for the Kerberos request. This may work in environments with appropriately configured DNS reverse lookup zones.

**LDAP connection**
After the ADWS connection attempt(s) fail LDAP is attempted. This also fails but in a different way. As with ADWS the Negotiate protocol is used but the Kerberos SPN takes the form of `host/fqdn` (e.g. `host/corp.domain.com`). This is also an invalid SPN as DCs do not register an SPN for the FQDN of their domain, presumably because it would result in duplicate SPNs for any domain with >1 DC.

The LDAP connection is only attempted once and I'm unsure how the target DC is selected (first `A` record returned by DNS query or maybe the IP address of the local system's logon server?). When the Kerberos authentication fails NTLM is attempted but fails as expected.

I'm unsure if there's a simple approach to workaround this as I don't have a suitable environment available where I can easily decrypt the signed LDAP messages. The initial unauthenticated bind to the domain's root DSE works, and there's a bunch of LDAP traffic leading up to the failed GSSAPI LDAP bind.

**Notes**
This is admittedly probably an edge-case as I expect the vast majority of domains do not disable NTLM authentication. But it occurs to me that this means when using the domain FQDN it will only work if NTLM is allowed. Kerberos is presumably always tried, but always fails, as the SPNs used are never valid except in unusual configurations where the required SPNs have been manually added.

**Comment by vletoux** [comment]
Thanks for this report

This is because I'm using IP resolution to find a DC ;-(
Indeed, I was in an environment where some DC are firewalled and I was not able to get 100% of the time DC connectivity.
Microsoft has then updated DsGetDCName (https://docs.microsoft.com/en-us/windows/win32/api/dsgetdc/nf-dsgetdc-dsgetdcnamea) to handle DS_WEB_SERVICE_REQUIRED so I can use this function now to locate a DC using its FQDN.

Are you in an environment where you can test again ? If yes, please contact me at support@pingcastle.com so I can send to you test programs.

Note: there is some hidden SPN thanks to "SPNMappings"

**Comment by vletoux** [comment]
as a workaround, can you try to enter directly the FQDN of the DC (not the domain) and force the LDAP connection (advanced menu) ?

**Comment by ralish** [comment]
> as a workaround, can you try to enter directly the FQDN of the DC (not the domain) and force the LDAP connection (advanced menu) ?

I just provide the FQDN of a DC instead of accepting the domain default and that works fine. No need to force an LDAP connection via the advanced menu and I'm pretty sure that ADWS connections work fine as well when providing a DC FQDN.

> Note: there is some hidden SPN thanks to "SPNMappings"

I don't think this is helpful in this scenario. The mappings are all for services but still require providing a valid computer name. In the cases documented earlier the computer name component of the SPN is invalid but the service name component is correct.

> Microsoft has then updated DsGetDCName (https://docs.microsoft.com/en-us/windows/win32/api/dsgetdc/nf-dsgetdc-dsgetdcnamea) to handle DS_WEB_SERVICE_REQUIRED so I can use this function now to locate a DC using its FQDN.

Excellent!

> Are you in an environment where you can test again ? If yes, please contact me at support@pingcastle.com so I can send to you test programs.

Sure, I'll send you an email.

**Comment by vletoux** [comment]
fixed by PingCastle 2.8.1.0
