### ISSUE TITLE
Check for Native administrator usage not showing correct data

### ISSUE THREAD

**Issue by rphlwnk** [vletoux/pingcastle#192]
Rule ID: P-AdminLogin

We have renamed and disabled the native "Administrator" account but PingCastle still reports usage of the account.
I have on none of my domaincontroller the attribute "LastLogonTimestamp" nor "LastLogonDate" present on this account.

Can the issue come from the fact that the account has never been used before? Or does PingCastle watch for another account and not the default "Administrator" called account?

**Comment by vletoux** [comment]
known issue.
Fixed in the upcoming version (usage of lastlogon attribute instead)
