### ISSUE TITLE
Feature request: Exclude objects inside a scpecific OU from analysis

### ISSUE THREAD

**Issue by red-erik** [vletoux/pingcastle#195]
Hello,
it would be fine to be able excluding objects inside specific OU, like "OU=To_Dimiss_or_Delete" that we need to maintain for legald hold reasons.
A parameter (I did not find it) would be great.

Regards,
Red.

**Comment by vletoux** [comment]
It's called "HoneyPot", located in PingCastle.exe.config
Beware: it's number is limited to avoid abuse.
