### ISSUE TITLE
pingcastle blocked at Gathering gpo data 

### ISSUE THREAD

**Issue by andreas65m** [vletoux/pingcastle#196]
Hello,

I launched pingcastle four days ago and it worked well.
Today it does not end.
The last displayed line is
Gathering gpo data

and the last lines in the log are

Done insert file
LdapQuery.BaseObject=DC=wobi,DC=ipes
LdapQuery.Filter=(objectClass=packageRegistration)
[11:38:13] Running enumeration
[11:38:13]Enumeration successful
Enumeration expires at 2023-09-08T10:08:13.9378957Z
Enumeration context is XXXXXXXXXXXXXXXXXXX ( changed by me ) 
[11:38:13]Getting Enumerate page 0
[11:38:13]Pull successful

Is there a way to have more details in the log to find the reason it blocks?

Greetings
Andreas

**Comment by vletoux** [comment]
please contact us through support@pingcastle.com for more analysis
