### ISSUE TITLE
Inactive Account Check Rule ID:S-Inactive

### ISSUE THREAD

**Issue by LiLaPhantom** [vletoux/pingcastle#198]
Hello together,
in my environment shows the S-Inactive Rule nearly every Useraccount as inactive.
In AD the lastlogon / lastlogontimestamp attribute is correct (Today morning), but Pingcastle counts this, and nearly every other account, as inactive.
The shown cmdlet works, lists 11 HealthMailbox accounts  an d 14 inactive Accounts. Thes are correct values, but pingcastle says 84% of all users are inactive.
this is not correcct.
Please excuse my english ;-)
regards Thomas

**Comment by vletoux** [comment]
this is a permission issue.
Run the program as admin or with a full token
