### ISSUE TITLE
Computer account password change - check report may not be accurate

### ISSUE THREAD

**Issue by neilpeel13** [vletoux/pingcastle#200]
(Enterprise license holder here - well, the company I work for holds it)

Pingcastle seems to use the lastlogondate to judge whether a computer account password has changed in the previous 90 days - rather than from the date the report was run. It produces some 'interesting' results.. Can this be changed to the report run date?

From Healthcheckrulestaledpwdlastset90.cs

if (c.PwdLastSet.AddDays(90) <= **c.LastLogonDate**)

**Comment by vletoux** [comment]
As I told you, the if is here to differenciate between the 90 days and the 45 days rule.
Real logic is coded here:
https://github.com/vletoux/pingcastle/blob/51412bf7ad13c861d78b95707f762403364af3a8/Healthcheck/HealthcheckAnalyzer.cs#L912-L927
