### ISSUE TITLE
PingCastle shows Azure AD Kerberos server as inactive (BIS)

### ISSUE THREAD

**Issue by RobinMJD** [vletoux/pingcastle#201]
Hello, this issue should be re-opened as it seems that the GUID is not static anymore, thus listing the AzureADKerberos computer object as a DC that is not updated (= false positive 15 pts issue).
![image](https://github.com/vletoux/pingcastle/assets/2559591/8fbcd208-71dc-4162-a097-583f5e96d57b)

I took 2 screenshots from 2 different AD Forests:
![image](https://github.com/vletoux/pingcastle/assets/2559591/1743345e-d7c9-4cbb-8dda-e5eb2e38a315)

![image](https://github.com/vletoux/pingcastle/assets/2559591/d6ce28b9-87bf-4d68-8bb2-164b56f5eee2)

**This "fake light RODC-like" object is used to allow Azure to be able to deliver TGTs for FIDO2 Security Keys and Windows Hello for Business sign-in on Hybrid-Joined devices.**

This object is created using the following documentation:
https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-security-key-on-premises#create-a-kerberos-server-object

Thanks in advance for the help.

_Originally posted by @RobinMJD in https://github.com/vletoux/pingcastle/issues/90#issuecomment-1814460513_

**Comment by RobinMJD** [comment]
Hello,

There is one more thing to add about false positive related to that object.

Rule "A-NTFRSOnSysvol" (Check if NTFRS is used to replicate SYSVOL) is falsely triggered too:
![image](https://github.com/vletoux/pingcastle/assets/2559591/988e1173-84f3-4524-a4bd-191c74ebcf86)

**Comment by An-dir** [comment]
I agree it should be excluded by some checks as it is no real RODC in most cases.
But to be sure it is an AzureAD fake RODC it should be verified with the `CN=900274c4-b7d2-43c8-90ee-00a9f650e335,CN=AzureAD,CN=System,<domain-DN>` configuration that should point to the DC.
Source: https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-passwordless-faqs#how-is-microsoft-entra-kerberos-linked-to-my-on-premises-active-directory-domain-services-environment

In some rare cases someone might have created a real DC with that name, so a general exclusion might be wrong too.
Does this path `CN=900274c4-b7d2-43c8-90ee-00a9f650e335,CN=AzureAD,CN=System,<domain-DN>` in your case point to the "fake RODC"?

**Comment by RobinMJD** [comment]
Hello, oh yes you're right I found the object in that place and the SID matched the computer object in its attributes:
<img width="423" alt="image" src="https://github.com/vletoux/pingcastle/assets/2559591/0994cf88-e610-41b7-8be9-b83cfa58e0db">

Is it possible to exclude that fake RODC from false positive issues then?

**Comment by An-dir** [comment]
So now I don't see anymore why it could not be excluded. The [logic is already in the code](https://github.com/vletoux/pingcastle/blob/master/Healthcheck/HealthcheckAnalyzer.cs#L901-L907) in a property called "AzureADKerberos". 
[The Rule S-DC-Inactive already has an exclusion.](https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaledInactiveDC.cs#L25-L28)

[The Rule S-DC-NotUpdated doesn't have an exclusion.](https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaledDCNotUpdated.cs)

@vletoux The Lines [L25-L28](https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaledInactiveDC.cs#L25-L28) from S-DC-Inactive should be copied to S-DC-NotUpdated
Additionally the [L26-L31](https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaleDCRegistration.cs#L26-L31) should be replaced by the [L25-L28](https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaledInactiveDC.cs#L25-L28)  in S-DCRegistration as well to use the new detailed check.

**Comment by vletoux** [comment]
I implemented the proposed change.
For licensed customers: be sure to verify this on the next published internal version
For others: be sure to check the next Beta version to be published end of January
