### ISSUE TITLE
"Export all computers" has always empty LAPS Columns

### ISSUE THREAD

**Issue by An-dir** [vletoux/pingcastle#203]
Hello

the "Export all computers" export hat the following LAPS relevant columns that seem always false/empty, atleast for LegacyLAPS, as this is what I can test for now:
- `LAPS` - always "false"
- `LAPSNew` - always "false"
- `LAPS last update (legacy LAPS)` - always empty
- `LAPS last update (Ms LAPS)` - always empty

Additionall the naming is misleading. I guess you meant "Windows LAPS" instead of "Ms LAPS". 
The **old LAPS** is now called "Legacy LAPS", "**Microsoft LAPS**" or "legacy Micrsoft LAPS"
The **new LAPS** is called "**Windows LAPS**" or "LAPS"
If you'd prefer creating a short name "MS-LAPS" and "WIN-LAPS" should do it, as "LAPSNew" won't always be new.
More to read: https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview#windows-laps-vs-legacy-microsoft-laps

The scanner "laps_bitlocker" returns laps data correctly for MS LAPS as that is what I was testing currently.

**Comment by An-dir** [comment]
Tested again with current beta without any luck. Will that be fixed in next release?

**Comment by An-dir** [comment]
Tested again with PingCastle 3.2.0.0 Beta1.1 (2024-01-25):
Still unchanged...
"LAPS","LAPSNew" are always false and "LAPS last update (legacy LAPS)", "LAPS last update (Ms LAPS)" are always empty.
Pingcastle was started elevated 

Testing Environment has a lot of legacy LAPS clients but no Windows LAPS clients.

**Comment by vletoux** [comment]
fixed in the next version
thanks for the report
