### ISSUE TITLE
S-PwdNeverExpires - Suggestion d'option -

### ISSUE THREAD

**Issue by Yickles** [vletoux/pingcastle#204]
Serait-il possible d'avoir un paramètre optionnel défini sur la règle "S-PwdNeverExpires" qui ne déclencherait pas l'alerte au niveau 2 pour les comptes de service (exemple en définissant une OU Dédiée "ServiceAccounts") 

(ou bien de pouvoir définir une "exception" en fonction de la présence de l'OU "ServiceAccount" dans le Distinguished name)

Je pense qu'il y a pas mal de société qui gèrent des comptes de service avec un mot de passe qui n'expire pas. (même si je comprends bien que ça ne semble pas être l'état de l'art)

En l'état, les domaines sont "bloqués" à un niveau de maturité 2 pour une occurrence qui peut être "maitrisée" / ou une "décision" d'entreprise.

j'aimerai votre avis le cas échéant sur ce cas particulier.

merci d'avance.

**Comment by vletoux** [comment]
J'ai ajouté pour la 3.2 le détail des comptes en question (du moment que le nombre soit limité) pour qu'ils puissent être mis en exception dans les versions Pro / Enterprise.
