### ISSUE TITLE
HeatlcheckRuleAnomalyLDAPSigningDisabled: suggestion to fix references

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#21]
I think the following references are unrelated to LDAP signing:
https://github.com/vletoux/pingcastle/blob/dac80958c5ef3b139fb157dadbe6f5a761b84d5e/Healthcheck/Rules/HeatlcheckRuleAnomalyLDAPSigningDisabled.cs#L17-L18

**Comment by vletoux** [comment]
Fixed in next version
