### ISSUE TITLE
Windows 11 23H2 reported as "Windows 11 (Build 22631)"

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#210]
Which is the correct build, but it probably should just say "Windows 11 23H2" (like it does for Windows 11 22H2 / Windows 10 22H2). This is under the _Computer Information_ -> _Operating Systems_ section.

**Comment by vletoux** [comment]
fixed in next version
also added the end of support date for the Windows 10/11 rule
https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information
thanks
