### ISSUE TITLE
Broken hyperlinks in AD report

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#211]
**GPO / Security settings**
> [Let Everyone permissions apply to anonymous users](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-access-let-everyone-permissions-apply-to-anonymous-users) ([Technical details](https://support.microsoft.com/en-us/kb/278259))

New link: Unclear as the referenced KB278259 article is no longer available.

**GPO / Audit settings**
> You can get a list of all audit settings with the command line: auditpol.exe /get /category:* ([source](https://blogs.technet.microsoft.com/askds/2011/03/11/getting-the-effective-audit-policy-in-windows-7-and-2008-r2/))

New link: https://techcommunity.microsoft.com/t5/ask-the-directory-services-team/getting-the-effective-audit-policy-in-windows-7-and-2008-r2/ba-p/399010

**Comment by vletoux** [comment]
fixed in the next version 
thanks
