### ISSUE TITLE
Add descriptive text and fix colour for MSV1_0\RestrictSendingNTLMTraffic

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#212]
In the _GPO -> Security settings_ section, if the "_MSV1_0\RestrictSendingNTLMTraffic_" setting is enabled the value column shows "_Enabled_" in red instead of green, which seems to be incorrect as restricting (i.e. disabling) outbound NTLM traffic is the secure setting.

The text itself should also probably be changed to something more descriptive. The setting name in the policy editor is:
> Network security: Restrict NTLM: Outgoing NTLM traffic to remote servers

Relevant hyperlink:
https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-restrict-ntlm-outgoing-ntlm-traffic-to-remote-servers

**Comment by vletoux** [comment]
fix for next version
