### ISSUE TITLE
Incorrect "no applicable GPO found" detections for GPO security settings

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#213]
The _GPO -> Security settings_ section contains a table which lists settings for which "_no applicable GPO has been found_". Many of the listed settings are in fact set in one or more GPOs. If it's helpful, here's the list of 13 detections with only the bottom two (bolded) being "legitimate":

- Guest account
- Allow anonymous SID/Name translation
- Let Everyone permissions apply to anonymous users
- Limit local account use of blank passwords to console logon only
- Sharing and security model for local accounts
- Do not store LAN Manager hash value on next password change
- Do not allow anonymous enumeration of SAM accounts and shares
- Do not allow anonymous enumeration of SAM accounts
- LDAP client signing requirements
- Refuse machine account password changes
- Microsoft network server: Digitally sign communications (if client agrees)
- **Recovery console: Allow automatic administrative logon**
- **Powershell: Turn on Module logging**

Happy to provide more info/diagnostic outputs but am not sure what's most helpful.

**Comment by vletoux** [comment]
I'm removing this section in 3.2
The root cause is that correct settings are not collected, thus showing them as not found.
