### ISSUE TITLE
Bug: Wrong --foreigndomain parameter ignored

### ISSUE THREAD

**Issue by ruppde** [vletoux/pingcastle#219]
A wrong  --foreigndomain parameter like e.g. `PingCastle.exe --foreigndomain doesnt_exist.no --healthcheck` is ignored and the default domain is scanned. 

Alse there's no indication of the problem in the output, the only telling sign is the total number of objects found in the domain.

Preferred behavior should be to exit, if the foreign domain can't be found. Second best an error message.

**Comment by vletoux** [comment]
to specify the target domain, the right paramter to use is --server
--foreigndomain is used for scanner
