### ISSUE TITLE
Example Report

### ISSUE THREAD

**Issue by SleepyLctl** [vletoux/pingcastle#231]
Hi, could you please provide example reports run on average/SMB/Enterprise AD for educational purposes? I am just looking for some reports from PingCastle, however I cannot find any. Thanks.

**Comment by vletoux** [comment]
It's on the website:
https://www.pingcastle.com/PingCastleFiles/ad_hc_test.mysmartlogon.com.html

More realistic reports contain private data and this is an issue to share it publicly
(can you get all consent for all of your users and are you confident to show a report about your vulnerabilities ?)
