### ISSUE TITLE
BUG : AzureAD - Check if users can consent to any app

### ISSUE THREAD

**Issue by s23hck** [vletoux/pingcastle#234]
Hello, 
To start, thank you for this tool :)
I just ran pingcastle in the latest version 3.2.0.1 option "2-azuread" and the report says:
"Users can consent to apps accessing company data on their behalf"

I just checked on the tenant, the option is indeed deactivated : 

![Capture d’écran du 2024-06-05 09-44-34](https://github.com/vletoux/pingcastle/assets/51639079/8de2b64b-07bb-4b17-9e2a-93f068644f4f)

Also linkedin connection is disabled :  

![Capture d’écran du 2024-06-05 09-45-29](https://github.com/vletoux/pingcastle/assets/51639079/63ebeb70-f214-4e88-bb03-dea536962ddd)

regards.

**Comment by vletoux** [comment]
I know.
Rule is disabled for next version
