### ISSUE TITLE
[Rules ] "The audit policy on domain controllers" - auditpol.exe

### ISSUE THREAD

**Issue by WiseLife42** [vletoux/pingcastle#236]
Hi,

A little information I noticed,
It seems that the role "The audit policy on domain controllers does not collect key events" in "Anomalies analysis" is only based on GPOs, I added the rules via the "auditpol.exe" command but I still have the anomaly returned in the report,

Kind Regards,

**Comment by vletoux** [comment]
this is by design.
Without privilege, we cannot connect to DC (and this is a good thing)
