### ISSUE TITLE
RiskRule A-DnsZoneUpdate2 finds DNS Zones that does not exist?

### ISSUE THREAD

**Issue by PorreKaj** [vletoux/pingcastle#237]
Hi, I'm struggling with the A-DnsZoneUpdate2 rule, that in one of our domains finds a DNS Zone configured with insecure updates.
The Zone however, does not exist on any of the domains DNS servers.
The Zone looks to be a reverse lookup zone, but unlike other reverse lookup zone it also contains "CNF: [GUIDHere]" in its name:

"1.1.1.in-addr.arpa CNF: [GUIDHere]"

I'm raising this issue to find out if there is a way to get PingCastle to mention more info in its report, to help remediating the problem.

**Comment by vletoux** [comment]
This is about a replication conflict object
(the modification was made twice at 2 different DC and only one was taken, the other was marked as CNF)

You have to delete it.
https://learn.microsoft.com/en-us/answers/questions/101494/all-about-active-directory-cnf-object-finding-vali
