### ISSUE TITLE
Fix the audit policy on domain controllers does not collect key events

### ISSUE THREAD

**Issue by Daymarvi** [vletoux/pingcastle#26]
Hello,

I executed the pingcastle 2.8 on a windows 2019 core AD servers. 

The reports is showing me that the audit kerberos authentication service is not enable on the GPO level
![image](https://user-images.githubusercontent.com/31985821/75015360-b6f4bf80-5488-11ea-8cc9-f5d4353f8371.png)

By applying the missing Audit logon settings and the "Audit Kerberos authentication service" into the GPO, part of the problem is solve. 
![image](https://user-images.githubusercontent.com/31985821/75015473-f4594d00-5488-11ea-874b-64a394e89439.png)
Only the "Audit Kerberos authentication service" seems missing from the report.
![image](https://user-images.githubusercontent.com/31985821/75015833-e526cf00-5489-11ea-884d-0aa4d24d9db5.png)

I executed that remotely and locally on the server and i have the same report.
Did i miss something ?
Thanks for your help

**Comment by vletoux** [comment]
It’s a bug: the first line in the GPO is ignored by the program

**Comment by Daymarvi** [comment]
Thanks for the feedback.

**Comment by vletoux** [comment]
fixed by PingCastle 2.8.1.0
