### ISSUE TITLE
Check the process of registration of computers to the domain

### ISSUE THREAD

**Issue by rrsit** [vletoux/pingcastle#27]
Hello,
what is "Check the process of registration of computers to the domain"  actually verifying?

according to best practices we have our default domain controllers policy unmodified, so it reads 

Add workstations to domain | NT AUTHORITY\Authenticated Users

to harden this setting, we have create a new GPO, linked to Domain Controllers OU, higher precedence than the DDCP, and it contains:

Add workstations to domain | BUILTIN\Administrators

so the pingcastle report should not flag this finding, but it does. is this a false positive?

**Comment by vletoux** [comment]
PingCastle doesn't check for precedance in GPO.
It is complex to do some analysis.
If you have a GPO which tells so, it won't be ok even if the GPO is not applied.
Also if you read the rule description, you will find the link with a domain attribute which manages also this setting
