### ISSUE TITLE
Audit Policy Check error 4908 & 4698

### ISSUE THREAD

**Issue by rrsit** [vletoux/pingcastle#28]
Pingcastle flags a missing audit policy setting for event id 4908

Audit Policy Change | No GPO check for audit success | Collect event 4908, to track special groups such as "administrators"

in our GPO -> advanced audit policy -> policy change -> audit audit policy change is set to successs

auditpol.exe /get /category:*  reports
Policy Change
  Audit Policy Change                     Success

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4908 says "This event is always logged regardless of the "Audit Policy Change" sub-category setting."

the same is true for

Audit object access | No GPO check for audit success | Collect event 4698, 4699, 4702 to track schedule tasks lifecycle

in gpo we have "audit other object access events" set to "success"
https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4698
auditpol.exe /get /category:*  reports
Object Access
  Other Object Access Events              Success

what am i missing?
all other audit settings report correctly and do not get flagged in pingcastle (2.8.1.0)

**Comment by vletoux** [comment]
You are writing issues when interpreting the report (2nd issue) while github is used only in code repos.
The support is made on a best effort basis (you didn't pay for that) at support@pingcastle.com and releases delivered only every 6 months.
Beware that there is 2 places to configure audit (simple & advanced)
Example of simple audit configuration:
![image](https://user-images.githubusercontent.com/10632326/75260769-64016c00-57ea-11ea-9370-6c2605e97bc2.png)
Double check and if you are still unable to get it, send an email to support@pingcastle.com with everything to reproduce the problem (such as a copy of the GPO)

**Comment by rrsit** [comment]
thanks. i have read the source code and fixed it myself.

HeatlcheckRuleAnomalyAuditDC.cs

line 98
{"AuditObjectAccess", new RequiredSimple("Audit object access", "Collect event 4698, 4699, 4702 to track schedule tasks lifecycle")},
should be
{"0CCE9227-69AE-11D9-BED3-505054503030", new RequiredSimple("Audit object access", "Collect event 4698, 4699, 4702 to track schedule tasks lifecycle")},

line 97
{"AuditPolicyChange", new RequiredSimple("Audit Policy Change", "Collect event 4908, to track special groups such as \"administrators\"")},
should be
{"0CCE922F-69AE-11D9-BED3-505054503030", new RequiredSimple("Audit Policy Change", "Collect event 4908, to track special groups such as \"administrators\"")},

source: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpac/77878370-0712-47cd-997d-b07053429f6d

best regards.

**Comment by vletoux** [comment]
You are mixing simple and advanced audit settings (not in the same place in the GPO settings) which are sharing the same names.
Internally the program saves a guid for advanced items and label for simple items.

**Comment by EHRETic** [comment]
> You are mixing simple and advanced audit settings (not in the same place in the GPO settings) which are sharing the same names.
> Internally the program saves a guid for advanced items and label for simple items.

Hi,

Sorry to interfere but as I'm using PingCastl to benchmark a security enhancement project, I can not stop thinking that PiongCastle should not test Simple Audit Policies IF Advanced ones are activated.

Simply because Advanced Audit Policies are overuling the simple ones.
My Audit GPOs are based on CIS standards which enforce the following setting (it is the defaut value but enforced for good reasons):

![image](https://user-images.githubusercontent.com/28634810/97329505-67685e00-1877-11eb-8e85-159a1a564e6d.png)

Not having simple Audit policies present doesn't mean you don't log the expected events, no? 😉

**Comment by vletoux** [comment]
It has been modified in 2.9.2 (not publically available except if you purchased a license)

**Comment by EHRETic** [comment]
> It has been modified in 2.9.2 (not publically available except if you purchased a license)

Hi, I thank you for that great news! 😉
