### ISSUE TITLE
--Graph switch

### ISSUE THREAD

**Issue by pwne-d** [vletoux/pingcastle#29]
Is the ''--graph" command line deprecated in v2.8.1? It seems to work in v2.7 but getting error - "unknown argument: --graph" error when using the following:

PingCastle.exe --graph --server mydomain.com

![pingcastle-v2 7 0](https://user-images.githubusercontent.com/12819665/75276603-77094180-57d4-11ea-92e3-dff206ad626f.JPG)
![pingcastle-v2 8 1](https://user-images.githubusercontent.com/12819665/75276806-da936f00-57d4-11ea-89f5-12e3277cc344.JPG)

**Comment by vletoux** [comment]
yes, because it has been merged with the healthcheck report
