### ISSUE TITLE
Crash in ExtractGPPPassword for Scheduledtasks.xml

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#3]
La méthode `ExtractGPPPassword` gère plusieurs fichiers XML avec champs `cpassword`.
Selon le fichier, le nom d'utilisateur peut se trouver dans des attributs différents.
Sont gérés les cas `accountName` et `userName` :
```csharp
                XmlNode accountNameNode = node.SelectSingleNode("Properties/@accountName");
                XmlNode userNameNode = node.SelectSingleNode("Properties/@userName");
                PasswordData.UserName = (accountNameNode != null ? accountNameNode.Value : userNameNode.Value);
```

Cependant les `Scheduledtasks.xml` utilisent le champ `runAs` qui n'est pas géré et qui déclenche un crash.

Pour référence : https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/Get-GPPPassword.ps1#L158

**Comment by vletoux** [comment]
fixed & merged (for the next release)
Thanks for the notification

**Comment by cnotin** [comment]
Thanks for fixing it!
