### ISSUE TITLE
v2.8.1.0 Missing users in Admin groups

### ISSUE THREAD

**Issue by ebfe90** [vletoux/pingcastle#31]
Hello,

I've tested the latest release on a parent forest and the report was missing users in the following groups:

- Administrators
- Domain Administrators
- Enterprise Administrators

The tool only reports the account Administrator.
I've launched pingcastle.exe with --log and the trace.log contains the missing users when the program enumerates these groups.

Could you help fix this problem?

Thank you

**Comment by vletoux** [comment]
Please contact support@pingcastle.com with the (missing) log file.
