### ISSUE TITLE
Checks based on SID

### ISSUE THREAD

**Issue by SOVentus** [vletoux/pingcastle#33]
Hi,
I noticed that in couple places were hardcoded names of privileged groups (Schema Administrators, Domain Admins, etc.). In my case names of them are different (e.g. Schema Administrators are Schema Admins) + due to language (e.g. German, Spanish) settings they very often totally don't match.

Is it possible to modify code a bit and use Well-Known SIDs instead?
https://support.microsoft.com/en-au/help/243330/well-known-security-identifiers-in-windows-operating-systems

**Comment by vletoux** [comment]
The tool has been designed to work in large & complex companies.
That means that when you centralize report, you need to understand the local admin name.
This is by design (and will break compatibility as the SID is not stored in the .xml file)
