### ISSUE TITLE
--nslimit says default is 5, but it is int.MaxValue

### ISSUE THREAD

**Issue by Genbox** [vletoux/pingcastle#35]
There is a small bug where the help output says the default number of users for null session enumeration is 5, but it is actually int.MaxValue.

Help Output:
> --nslimit <number>: Limit the number of users to enumerate (default: 5)

Parser code in Program.cs:
```csharp
if (!int.TryParse(args[++i], out NullSessionScanner.NullSessionEnumerationLimit))
{
	WriteInRed("argument for --nslimit is not a valid value (typically: 5)");
	return false;
}
```

Default value in NullSessionScanner.cs:
```csharp
public static int NullSessionEnumerationLimit = int.MaxValue;
```

There are no other places in the code where the value is set.

**Comment by vletoux** [comment]
Thanks for the report.
Fixed in the next version

```csharp
Console.WriteLine("    --nslimit <number>: Limit the number of users to enumerate (default: unlimited)");
```
