### ISSUE TITLE
NullSession and NullSessionTrust scanners output comma instead of tab

### ISSUE THREAD

**Issue by Genbox** [vletoux/pingcastle#36]
NullSessionScanner outputs a mix of TSV and CSV:
```
DisplayAdvancement(computer,"Null session is disabled");
sb.Append(computer);
sb.Append(",None,");
```

Notice it outputs comma. I also think the comma after "None" might be a bug.
The same thing applies to NullSessionTrustScanner, except it outputs CSV only.

**Comment by vletoux** [comment]
Thanks

Fixed for the next version - do not forget to test it again when It'll be in beta
Was also present in a few other scanners (errors and null session trusts)
