### ISSUE TITLE
2.8.1.0 version not automatically switching to LDAP when ADWS is unavailable

### ISSUE THREAD

**Issue by pruno7** [vletoux/pingcastle#37]
I tried to run pingcastle 2.8.1.0 on a DC that does not have ADWS available and the following message appeared:

`An exception occured when doing the task: Perform analysis for [DOMAIN]
Exception: Connection to net.tcp://[DC]:9389/ActiveDirectoryWebServices/Windows/Resource impossible. The connection attempt lasted for a period of 00:00:21.0520035. TCP error code 10060: A connection attempt failed because the connected party did not respond properly after a certain amount of time, or an established connection failed because the connection host did not respond [IP]:9389.`

I had to go the options to force the usage of LDAPOnly in order to run the tool properly. It however should switch automatically with the default option (ADWSThenLDAP) ?

**Comment by vletoux** [comment]
Fixed in 2.9 beta
