### ISSUE TITLE
Suggestion: add pagination in long tables, or add folding to sections

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#39]
At the bottom of a report we have a few sections with tables including many detailed info. For example "Audit settings", "Privileges", "GPO Login script", etc.
In large domains those tables can have many entries which makes it harder to skip them and reach the next section.
Therefore I suggest adding a pagination feature to the tables (to limit them to 10 visible entries for example), or a way to skip the section and go to the next (for example by "folding" the section).

**Comment by vletoux** [comment]
Datatables is used internally to do the work.
https://datatables.net/examples/basic_init/alt_pagination.html

**Comment by cnotin** [comment]
Indeed! I see why it fails and shows as normal table...
See #40 + another issue I have to investigate

**Comment by cnotin** [comment]
Nevermind #40 (closed) it was a mistake on my side.
Let me dive into the 2nd issue -> the table of "Foreign domain involved" in "Control Path Analysis" is malformed and thus datatable fails and it only applies to table before this one but not after!

**Comment by cnotin** [comment]
Here is the root cause: #42

**Comment by cnotin** [comment]
As discussed, potentially implemented later :)

**Comment by vletoux** [comment]
Available in 2.9 beta
