### ISSUE TITLE
Add path parameter for health checks in command line mode

### ISSUE THREAD

**Issue by mrclschstr** [vletoux/pingcastle#4]
I'm searching for a path parameter in command line mode to specify the output folders for the HTML and XML files of a health check. It seems like this is not implemented yet? Would be great if this could be added in the next release.

**Comment by vletoux** [comment]
The program generate the file(s) in the current directory.
Current directory <> directory where PingCastle.exe is stored.
You can change it using a shortcut or directly in the command line by running it in another directory (specify the full path of PingCastle.exe)
