### ISSUE TITLE
HTML Report: CSP issue

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#40]
The HTML report contains a Content-Security Policy which is a good thing. Hashes are computed for imported scripts:
https://github.com/vletoux/pingcastle/blob/523fd754be5df7dc1f39debe319c15608607b411/Report/ReportBase.cs#L100-L103

Including inline scripts, for example:
https://github.com/vletoux/pingcastle/blob/523fd754be5df7dc1f39debe319c15608607b411/Report/ReportHealthCheckRules.cs#L38-L40

However, I noticed a warning in the Chrome console:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'sha256-t+xSDjAl7us/fSDwXMOUEX9O//OSNHhrky8hNs6bz6Q=' 'sha256-PgJlwxywHc63YBGsq97e404DO74MOKtKwEeTHyvPybI=' 'sha256-4aSc9Sgpav/KkHR9Etdg091GCnpW2pXdZAbCOIAwKxE=' 'sha256-Yt4VyG+DwKljtX/ozxDNG8QGP8x73pm7mkSE5m4RIU0=' 'sha256-+6QIuqOxYuMrW8s/xpzzzYSymjfvJYQ3yzV/UKyokEU=' 'sha256-vGrCRkYPwv1G/K8Y22/y1aWwBVPXBwFkF5KYwVutiJI=' 'sha256-6Y3BjZXxsrbZfGSuW0JCUYQ2ua1X1Tm8FsBzFKyJg50=' 'sha256-oh9nNTrYGBinUFrNl9SzIpKK4yR2iqIHbJjzX6Rl5ho='  'unsafe-inline'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```
The mentioned line refers to this code:
https://github.com/vletoux/pingcastle/blob/523fd754be5df7dc1f39debe319c15608607b411/Report/ReportHealthCheckRules.cs#L38-L40

I think the computed hash is incorrect.

Moreover, even if I don't think it's the cause of the issue here, `unsafe-inline` is specified:
https://github.com/vletoux/pingcastle/blob/523fd754be5df7dc1f39debe319c15608607b411/Report/ReportBase.cs#L104
But as Chrome says:
> Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list

**Comment by cnotin** [comment]
Nevermind I didn't reproduce it

**Comment by vletoux** [comment]
Browsers or plugin are know to inject silently JavaScript
For example google with its analytics script.
This is one of the reason I did implement it
