### ISSUE TITLE
PingCastle logo has hyperlink to unusual/broken link

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#46]
In reports generated by v2.9.0.0 Beta the PingCastle logo (top left of report) is also a hyperlink in the form:
`https://www.pingcastle.com/reports/<id>//#`

The `<id>` appears to uniquely identify the scanned domain. Accessing the link itself returns a 403 response and a blank page.

EDIT: This affects other hyperlinks in the report as it's set in the `<base>` tag within `<head>`.

**Comment by vletoux** [comment]
The feature was not intended to be public.
I commented out the <base> tag for Beta 2.
