### ISSUE TITLE
Potentially incorrect DC audit policy detections

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#47]
The v2.9.0.0 Beta flags some issues with audit policy on DCs which are questionable:
![image](https://user-images.githubusercontent.com/3214803/89027377-bb919e00-d36d-11ea-8af1-1991250d9dd4.png)

**Account Logon / Other Account Logon Events**
The referenced event is captured by success events from the [Audit Logon/Logoff -> Audit Logon](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-logon) sub-category. Microsoft's documentation states the [Account Logon -> Audit Other Account Logon Events](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-other-account-logon-events) sub-category doesn't presently log any events.

**Audit policy change**
The referenced event is captured by success events from the [Policy Change -> Audit Audit Policy Change](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-audit-policy-change) advanced audit policy sub-category. It's correct that the policy is not set, but it's also redundant when the corresponding advanced audit policy sub-category is enabled, so shouldn't be a detection?

**Audit object access**
The referenced events are captured by by success events from the [Object Access -> Audit Other Object Access Events](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/audit-other-object-access-events) advanced audit policy sub-category. Same general issue as the *Audit policy change* detection above.

**Comment by vletoux** [comment]
It comes straight from https://adsecurity.org/?p=3377, chapter "Domain Controller Events to Monitor (Event Logs)"

Example, 4648 event is indicated coming from "Audit Logon" and from "Audit Other Account Logon Events".

Given my source, can you elaborate?
I don't understand given this source where the problem is.

**Comment by vletoux** [comment]
That means adsecurity.org is wrong?

**Comment by ralish** [comment]
Hmm, I'll take a close look once I get the chance. The above however is based off Microsoft's documentation, so something is likely not quite right ...

**Comment by ralish** [comment]
So taking a look at the _DC-Events_ spreadsheet:

- Event 4648 is listed twice with one of the two listings being the correct audit category. So yes, I think this one is a mistake. Either that, or Microsoft's documentation is wrong.
- The recommendation for Event 4908 to enable the _Audit policy change_ category isn't "wrong", but it is redundant if the referenced advanced audit policy category is enabled. The latter is I think generally preferable due to being more fine-grained. As long as one of them is enabled, the referenced event is being recorded, so it's not a security misconfiguration.
- Same as above for the remaining three events.

**Comment by vletoux** [comment]
Sorry, it's too late for this release.
The change are not trivial and needs some review which is incompatible with this release timeline

**Comment by ralish** [comment]
That's fine, it just means in some configurations audit policy detections will be incorrect. Let's leave the issue open until it's addressed in the next release?

**Comment by vletoux** [comment]
removed for the next version the requirement to have these 3 audit policies
