### ISSUE TITLE
Inconsistency in krbtgt password rotation check

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#48]
The changelog for the v2.9.0.0 Beta states the `krbtgt` account password rotation check has been updated to trigger only after a year but generated reports still reference 40 days:
_The password of the krbtgt account should be changed twice every 40 days using this script_

It's not clear if this is intentional or an oversight. If intentional, the wording could be tweaked to make it clear this is a recommendation but not a vulnerability and will only be flagged after 1 year without rotation.

**Comment by vletoux** [comment]
Change it to "The password of the krbtgt account should be changed twice regularly (between 40 days and one year or at each admin departure) using this script" for beta 2.
Better phrasing welcomed

**Comment by ralish** [comment]
How about:
> The account password for the `krbtgt` account should be rotated twice yearly at a minimum. More frequent password rotations are recommended, with 40 days the current recommendation by ANSSI. Additional rotations based on external events, such as departure of an employee who had privileged network access, are also strongly recommended.

**Comment by vletoux** [comment]
Is that ok ?
![image](https://user-images.githubusercontent.com/10632326/89097119-617bf180-d3dc-11ea-94d3-5b7b793023b0.png)

**Comment by vletoux** [comment]
updated in beta 2
