### ISSUE TITLE
Incorrect value for Max Password Age for PSO policies

### ISSUE THREAD

**Issue by ralish** [vletoux/pingcastle#49]
The v2.9.0.0 Beta is returning an incorrect result for the _Max Password Age_ of some Fine-Grained Password Policies. When no maximum password age is configured for an FGPP the report shows the _Maximum Password Age_ as 10675199 day(s) instead of the expected _Never expires_ (correctly displayed when configured as such in the _Default Domain Policy_).

If helpful the relevant attributes as shown in ADSI Edit for the affected `msDS-PasswordSettings` object are:

- `msDS-MinimumPasswordAge : (none)`
- `msDS-MaximumPasswordAge : (never)`

**Comment by vletoux** [comment]
The problem was present in past version and located here:
https://github.com/vletoux/pingcastle/blob/9e237effe6f14a8edfd601816406f1d45f4e6686/Healthcheck/HealthcheckAnalyzer.cs#L3396
msDS-MinimumPasswordAge was written instead of msDS-MaximumPasswordAge
Fix in next Beta
