### ISSUE TITLE
v2.6.0.0 localadmin scanner only collects local admin of domain controller

### ISSUE THREAD

**Issue by duummee** [vletoux/pingcastle#5]
Running v2.6.0.0 from cli with command "pingcastle --scanner localadmin", the result creates text file containing only the local admins of the domain controller. 

Expected behaviour like v.2.5 where the same command outputs a text file with the local admin of all domain-joined computers.

**Comment by vletoux** [comment]
You are right, the behavior with --scmode-single is inverted (it should scan 1 computer instead of all computers).
Please add --scmode-single as a workaround. This will be fixed for the next version (July, 31th)

**Comment by vletoux** [comment]
change == by != in https://github.com/vletoux/pingcastle/blob/master/Scanners/ScannerBase.cs#L62 fixes the problem.
Fixed in 2.7
