### ISSUE TITLE
BSI links are broken...

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#52]
It looks like that the BSI (German gov) changed some links...
https://github.com/vletoux/pingcastle/blob/523fd754be5df7dc1f39debe319c15608607b411/Rules/RuleAttribute.cs#L256-L267

I didn't find an exact equivalence to suggest

**Comment by vletoux** [comment]
BSI references removed as the document is not online anymore

**Comment by cnotin** [comment]
Well :)
