### ISSUE TITLE
Rule about "RODC Denied Group" has false positives

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#53]
It looks like that this rule "The Denied RODC Password Replication Group group has some of its default members missing" has false positives for those groups:

- Enterprise Administrators
- Schema Administrators

I don't have the code to check but I guess it's because those are defined at forest root level, instead of within the current domain :)

**Comment by vletoux** [comment]
this is the code
![image](https://user-images.githubusercontent.com/10632326/89110754-3af69e80-d44e-11ea-9555-c453041a73ce.png)

**Comment by vletoux** [comment]
indeed, the enterprise admin SID is wrong if it is a child domain

**Comment by vletoux** [comment]
Now
![image](https://user-images.githubusercontent.com/10632326/89110834-06cfad80-d44f-11ea-9cc6-fe23cf8a17a9.png)

**Comment by cnotin** [comment]
Nice :) thanks!
