### ISSUE TITLE
Disparition de l'item "Relatively high number of inactive user acounts (more than 15%)"

### ISSUE THREAD

**Issue by hcx35** [vletoux/pingcastle#54]
J'ai vérifié les sorties d'un même domaine avec les versions 2.8.1.0 et v2.9.0beta.
L'item: Relatively high number of inactive user acounts (more than 15%) a disparue de la beta.

**Comment by vletoux** [comment]
Quote from the change log "Change the threshold of S-Inactive from 15 to 25% to match user_accounts_dormant rule"
