### ISSUE TITLE
Mispelling in 'A bogus Windows 2016 installation has granted to much right...'

### ISSUE THREAD

**Issue by Coldfirex** [vletoux/pingcastle#6]
Howdy,
Version: 2.6.0.0

Under the Privileged accounts rule details section:
Section "A bogus Windows 2016 installation has granted to much right to the Enterprise Key Admins group" should read as "A bogus Windows 2016 installation has granted too many rights to the Enterprise Key Admins group"

In the same section sub-title of "Ensure that boggus Windows 2016 AD prep did not introduce vulnerabilities" should read as "Ensure that a bogus Windows 2016 AD prep did not introduce vulnerabilities"

**Comment by vletoux** [comment]
Thanks for the report.
Fixed in 2.7

**Comment by Coldfirex** [comment]
I have several more misspellings I came across.  Would you like for me to keep submitting them?  If so, do you want a ticket for each section or one big one?

**Comment by vletoux** [comment]
Just modify directly this file and send me a copy at contact@pingcastle.com
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/RuleDescription.resx

**Comment by vletoux** [comment]
Thanks for your contribution that will be integrated in PingCastle 2.7.0
