### ISSUE TITLE
"Presence of unknown accounts" cant resolve SIDs

### ISSUE THREAD

**Issue by phl0x1** [vletoux/pingcastle#61]
The "Presence of unknown accounts" rule is triggered if I run PingCastle between forests. There is no trust between them.
The rule is triggered because it can't resolve SIDs correctly, even well-known one.
The user I'm using is a standard authenticated user, nothing special.

Interestingly these 4 SIDs appear in all forest with the same setup (no trust/readuser).

![FailedRule](https://user-images.githubusercontent.com/55682291/93601728-e9847d80-f9c1-11ea-9f48-53e8b339c7b2.PNG)

.\PingCastle.exe --healthcheck --server contoso.com --user readuser --password ([System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR))

**Comment by vletoux** [comment]
You can see here that PingCastle is using the server to resolve the SID:
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/HealthcheckAnalyzer.cs#L1491

Maybe you address the server with an IP. The PingCastle program is using the dnsHost property of the rootDse object, which is the FQDN of the DC. Maybe you can't resolve the fqdn locally or there is a firewall preventing the resolution

**Comment by phl0x1** [comment]
Thanks for you reply.

The connection gets established by using the domain name "contoso.com", even if I use the server FQDN "dc.contoso.com" I get the same result in the report.
Both port 9389 and 389 are open and accessible. (tested with tnc and --protocol ldaponly/adwsonly)

The log shows the following error:
Error 5 when translating S-1-5-21-x-x-x-553 on DC1.contoso.com

I also tested the behaviour in my lab. The resolution of SID/Name was fine. So the resolution is working in general and no bug/issue in PingCastle itself.

What does Error 5 mean?

**Comment by vletoux** [comment]
5 means Access Denied
I've to look on how the identity of the account can be impersonated because it is done at a lower level

**Comment by vletoux** [comment]
Can you contact support@pingcastle.com to test custom build ?
