### ISSUE TITLE
Typo on Trusts section in HC report

### ISSUE THREAD

**Issue by CyrilleFranchet** [vletoux/pingcastle#63]
Hi,

I think that the text displayed in the Trusts section inside the health check report is incorrect.
Text presents in indicators section is correct by the way.

**Comment by vletoux** [comment]
can you pinpoint the exact location ?
(aka: copy paste the content of the text which is not ok and the one which is correct)
Indeed, there are several location, and if it has not been fixed, this is because we didn't see it

**Comment by CyrilleFranchet** [comment]
Line 198 in Report/ReportHealthCheckSingle.cs.
Replace :
GenerateSubIndicator("Trusts", Report.GlobalScore, Report.TrustScore, "It is about operations related to user or computer objects");
by
GenerateSubIndicator("Trusts", Report.GlobalScore, Report.TrustScore, "It is about links between two Active Directories");

**Comment by vletoux** [comment]
well spotted.
Will be updated in the next version
