### ISSUE TITLE
False positive in DCSubnetMissing due to only 1500 subnets returned from a Site

### ISSUE THREAD

**Issue by cnotin** [vletoux/pingcastle#66]
I noticed a false positive with the DCSubnetMissing rule where a DC IP was indeed in a declared subnet. I debugged the issue and found that `GenerateNetworkData` only collects the first 1500 Subnets of a Site. This looks similar to the default LDAP query policy which limits results to 1500, but I do not know how it is handled by ADWS. I see that the code supports paging, but maybe it should be applied to results' properties too?
Sorry for not proposing a PR...

**Comment by vletoux** [comment]
Which LDAP Extended oid are you talking about ?
I can indeed push the OID I need with ADWS

**Comment by cnotin** [comment]
The subnet info is in the "siteObjectBL" attribute:
https://github.com/vletoux/pingcastle/blob/68e57eb46262f9e912cd608da3f502660ac69081/Healthcheck/HealthcheckAnalyzer.cs#L3818
https://github.com/vletoux/pingcastle/blob/68e57eb46262f9e912cd608da3f502660ac69081/Healthcheck/HealthcheckAnalyzer.cs#L3831-L3837
So that would be `1.2.840.113556.1.4.513`

Note that it is already collected. The issue is that only the first 1500 siteObjectBL attributes are retrieved (not the Sites themselves)...

**Comment by vletoux** [comment]
I'm talking about this part of the code:
https://github.com/vletoux/pingcastle/blob/master/ADWS/ADWSConnection.cs#L363-L367
and OID like this one 1.2.840.113556.1.4.801 that are defined here:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/3c5e87db-4728-4f29-b164-01dd7d7391ea

(you said that by default output are limited to 1500 items)

**Comment by cnotin** [comment]
My observation is that if I have 1 Site (objectclass=Site) with 3000 associated Subnets ("siteObjectBL" attribute), PingCastle will only get the first 1500 Subnets, which then can generates false positives in the DCSubnetMissing rule.

I have no idea of what could be the solution (otherwise you would have gotten a PR :) ). But when doing some research I discovered this 1500 limitation with LDAP (`MaxValRange` setting) but perhaps it is not related... Even in classic LDAP, I think it applies to the items returned but I do not know if it applies to the attributes of those objects...

**Comment by vletoux** [comment]
ok this one:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/e27b48db-6f82-44cd-9038-2e54f790cc1f

**Comment by vletoux** [comment]
the 1500 limit is defined on this page:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/3f0137a1-63df-400c-bf97-e1040f055a99

**Comment by vletoux** [comment]
fixed in the next version of PingCastle
