### ISSUE TITLE
pingcastlereport.exe missing

### ISSUE THREAD

**Issue by johnjohnsp1** [vletoux/pingcastle#68]
Hello,
i do compile pingcastle from source, everything is fine with this output:
2>  PingCastleAutoUpdater -> C:\temp\pingcastle\bin\Debug\PingCastleAutoUpdater.exe
1>  PingCastle -> C:\temp\pingcastle\bin\Debug\PingCastle.exe

but i dont see anymore the pingcastlereport.exe like the previuos release (2.7.1.1) in order to build ppt report.
i miss something ?

using vstudio2019 enterprise edition, but even downloading the release from github that section is missing.
i just found it on the rel 2.7.1.1

thanks

**Comment by vletoux** [comment]
PingCastleReport was not part of the source published and the .exe distributed is not supported anymore as part of the free version.
