### ISSUE TITLE
Problem with Fine Grained Password Policy lockout duration report

### ISSUE THREAD

**Issue by TotoTataJa** [vletoux/pingcastle#7]
Hi,
I love your work, thanks for this incredible tool.
After an AD audit at a customer, I noticed a slight problem in the report regarding Fine Grained Password Policy lockout duration.
The account lockout duration is set to 30 minutes and the report tells me 6 minutes.
I don't know if it's a bug or a calculation you're doing.
I have reproduced the problem in a lab just to be sure.

See attached pics
Thanks again 
![2019-04-04_15-51-32](https://user-images.githubusercontent.com/33195672/55561252-212a3780-56f2-11e9-93a3-1cb6232ce82c.jpg)
![2019-04-04_15-54-28](https://user-images.githubusercontent.com/33195672/55561253-212a3780-56f2-11e9-88f9-ddbbbab60b17.jpg)

**Comment by vletoux** [comment]
The translation is performed in these 2 lines
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/HealthcheckAnalyzer.cs#L2804-L2805
replacing 3000000000 by 15000000000 should fixed the problem.
However, I've to do additional tests to be 100% sure.

**Comment by vletoux** [comment]
I was wrong. 3000000000 needs to be replaced by 600000000.
Bug confirmed.
Fixed in 2.7.0 (July, 31th)
