### ISSUE TITLE
P-ProtectedUsers : Incorrect Trigger value

### ISSUE THREAD

**Issue by Nioubi24** [vletoux/pingcastle#73]
Hi,
The rules details specifies "_Please also note that a few links (see below) recommends that at least one account is kept outside of the group Protected Users in case there is a permission problem. That's why this rule is not triggered if only one account is not protected._"
And a little further "10 points if the occurence is greater or equals than 1"... ==> inconsistency with the preceding sentence

In fact, the rule triggers with only 1 account in the list... ;-(   

1) the sentence should be "10 points if the occurence is greater than 1", and 
2) the rule shoudn't trigger with only one account in the "User" list

Regards

**Comment by vletoux** [comment]
it is fixed in the next version.
You'll have to wait until it is released.
(unless you have a support contract)

br
Vincent
