### ISSUE TITLE
S-ADRegistration 

### ISSUE THREAD

**Issue by Nioubi24** [vletoux/pingcastle#75]
Hi,

As specified in [https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/add-workstations-to-domain](url), a GPO exist on my AD, which affects some users, identified as something like "_authorized members of the IT_" on PCs, without any "admin" privileges in DC... but these users have the "_add workstation to domain"_ privilege.

So, these are not "_basic users_", and "_basic users_" can not add extra computers to the domain.... but the PingCastle rule triggers....  for me this is just like a "_false positive detection_"... ;-(   

Regards

**Comment by vletoux** [comment]
What is the problem ?
The rule check both for the attribute at the root of the domain AND the domain users GPO
having this attribute set AND a GPO set to different user setting this privilege doesn't trigger the rule

The only case not covered correctly is if the domain user GPO is overriden by another GPO which removes the privilege

**Comment by Nioubi24** [comment]
Hi,
Please, don't misunderstand me... the software is great and efficient, but I've got some "_false positives_"... that's all. And I take some of my time to describe them to make - eventually - a more precise tool, or to understand why a specific rule could be triggered.

I totally agree with you on the vulnerability... but :
1) the GPO is at the root of the domain
2) a group of users not the _"authenticated users_" default group - is defined in this GPO
3) There is no other GPO to override the privileges 


The rule triggers... so... ;-(

Is there something more precise I could verify, like in the XML file or something ?

Regards

**Comment by vletoux** [comment]
The rule code is described here:
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaleADRegistrationEnabled.cs

I suggest you run the trace (advanced => log) to generate the log file and point the GPO having this problem

**Comment by Nioubi24** [comment]
Hi,
Thank you for your answer on the PingCastle's "Log" file.

So : 

1) My apologies, my fault, after reading the log file and checking my system... there was a priority problem on my GPOs on the DCs... corrected and verified (gpresult) ;-(
2) The rule still triggers in the report
3) I've read the Rule code... if my understanding is good, the rule triggers if **any** policy contains "_Authenticated users_"... (or "Anonymous"...). Ok.
But, if this SeMachineAccountPrivilege parameter is present in the "_Default Domain Controllers Policy"_ which is not recommended to modify, and in a second GPO (with - of course - the proper priority order) with a different value (another Security Group)... the rule will still trigger...

The log file is clear : "SeMachineAccountPrivilege found in GPO Default Domain Controllers Policy
  matched"... yes that's true... but - with the  priority order of GPOs - that doen't imply that this "SeMachineAccountPrivilege" is applied by this default GPO... in my case it is currently overridden by another GPO.

Thanks.
Regards

**Comment by akennerly** [comment]
@Nioubi24 PingCastle doesn't know that another GPO is negating what's in the Default Domain Controllers GPO.

If you're intention is to remove "Authenticated Users" from adding machines then remove it from the Default Domain Controllers Policy or ignore this rule in PingCastle if you're sure you policy order mitigates the risk.

**Comment by Nioubi24** [comment]
@akennerly : Ok. Thanks for your advice. In my case, the situation is now clear on my system.... 

I merely think that the report can be improve to be even more relevant.

> PingCastle doesn't know that another GPO is negating what's in the Default Domain Controllers GPO

Ok, PingCastle may not be aware of another higher priority GPO... fine, and clear for me. 

Nevertheless, IMHO - a minima - in the report, the user should be informed in the detail section of the rule of the possibilty that another GPO - whith higher priority than the default GPO - may be present and mitigates the risk... and he needs to verify this possibilty.  

That's all what my posts were about...

Regards

**Comment by vletoux** [comment]
I've written a code that check for GPO overwrite on this case.
I need volonteers to test it.
Contact me at support@pingcastle.com please to test it.
