### ISSUE TITLE
PingCastle fails to run

### ISSUE THREAD

**Issue by AngryManJew** [vletoux/pingcastle#76]
Hey,

Lately I have been using PingCastle on a weekly basis at my organization, and first of all I must admit this tool is pretty amazing and thank you for your contribution.

As for the problem, recently I have been trying to generate healthcheck reports and it fails every time with an error that tries to indicate for AD corruption.
So after I tried a couple of other methods to generate the report (for example - running the report from another desktop, from a server, different users I have etc.) and validated that the ntds.dit integrity is fine and validated that the replication status is valid, I tried to run the healthcheck once again but now with the log enabled, and the error received there is as such:

`ErrorCode: -2147024662`
`ExtendedError: 234`
`ExtendedErrorMessage: Calling GetNextRow can potentially return more results.`
`numberOfObjectAlreadyExtracted=233`
`[Red]An exception occured while querying the Active Directory`
`[Red]Exception: More data is available.`
`(Calling GetNextRow can potentially return more results.)`
`[Red]This error occurs when the Active Directory server is under load`
`[Red]Suggestion: try again and if the error persists check AD for corruption`

From what I read, similar problems have occurred to people who have set the PageSize of the DirectorySearcher to 500 instead of 1000, and also to whom who have set a SizeLimit (but the size limit is not the case here)

I hope I have provided enough information and I hope the issue could be fixed

**Comment by vletoux** [comment]
on 100% of reported cases until now, it was an ad database corruption
ntdsutil has a repair option that fixes it
If you enable the traces, you'll see the exact AD request that is an error, and you can reproduce it with an independant AD query util (such as powershell)

**Comment by AngryManJew** [comment]
I checked for corruption and as I said, the ntds.dit is fine and not corrupted

Also, the LDAPQuery which causes my failures is `(|(unixUserPassword=*)(userPassword=*)`
I used `Get-ADObject -LDAPFilter` with the given filter to try and reproduce the result of the query for the given filter, but it failed because the timeout limit has been exceeded.

I tried to play a little with the ResultPageSize and had interesting results - 
1. When I set the ResultPageSize to 500 it had the same timeout error
2. When I set the ResultPageSize to 1000, again, same problem
3. When I set the ResultPageSize to 50, it started returning values

**Comment by vletoux** [comment]
well: you reproduced it without PingCastle, so this is not an issue with our software.
(the page size force or exclude the retrieval of the record which is causing troubles)

**Comment by AngryManJew** [comment]
In any case, I think that perhaps it is a good idea to enable large domains to customize the PageSize, because lowering it enables the ldap query to finish without errors

**Comment by vletoux** [comment]
And how many results are you retrieving ?
The number defined as PageSize ?

**Comment by AngryManJew** [comment]
It returns all the ADObjects that comply with the LDAPFilter, the only difference is that the batches it is being sent at is based on the setting of the PageSize

**Comment by AngryManJew** [comment]
Update - 

I edited the config file of the ADWS to check if increasing the MaxPullTimeout and OperationTimeout to 5 minutes instead of 2 minutes will affect the process, but it was meaningless as the healthcheck report generation still failed. 
I decided to scheme all of the errors generated from the trace log, and in all the cases which the ADWS failed to process the request, it seems like there is a configured timeout of 1 minute for each operation (maybe because of WCF default setting)

The Exception thrown is:
`Exception: This request operation sent to net.tcp//<dc-fqdn>:9389/ActiveDirectoryWebServices/Windows/Enumeration did not receive a reply within the configured timeout (00:01:00). The time allotted to this operation may have been a portion of a longer timeout. This may be because the service is still processing the operation or because the service was unable to send a reply message. Please consider increasig the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client`

Now, I can assure ADWS is working fine because the same error is thrown on a DC which I have not tinkered with its adws config file, and probably the reason for the timeout is that the ADWS is still processing the operation

Is there anything that could be set on the config file of PingCastle to increase the OperationTimeout from 1 minute to even longer?

**Comment by vletoux** [comment]
Did you try to force LDAP ? (--protocol LDAPOnly or advanced menu)

**Comment by AngryManJew** [comment]
I tried running it on LDAPOnly, but it still failed with the error I mentioned in my previous comments - 
`ErrorCode: -2147024662`
`ExtendedError: 234`
`ExtendedErrorMessage: Calling GetNextRow can potentially return more results.`
`numberOfObjectAlreadyExtracted=233`
`[Red]An exception occured while querying the Active Directory`
`[Red]Exception: More data is available.`
`(Calling GetNextRow can potentially return more results.)`
`[Red]This error occurs when the Active Directory server is under load`
`[Red]Suggestion: try again and if the error persists check AD for corruption`

And as I stated, there is no corruption what so ever, and when I have done an LDAP query using powershell, but with a much smaller ResultPageSize, I do get all the results for the query (also important to mention, every time it failed, it was due to the `(|(unixUserPassword=*)(userPassword=*)` filter)

**Comment by adminsdholder** [comment]
Any solution to this? Having same problem. Query from trace log fails in large domain.

`(|(unixUserPassword=*)(userPassword=*))`

Fails outside of tool. Customizing PageSize outside of tool allows query to finish. Any chance this can be modified to accommodate larger domains as suggested in this thread? I see no option to allow tool to complete without modifying the query.

**Comment by vletoux** [comment]
The next version includes a selector to optimize the ldap query

customers who have purchased a license can already access it
