### ISSUE TITLE
Exception when some LDAP attribute seems to be missing

### ISSUE THREAD

**Issue by foobarmuh** [vletoux/pingcastle#77]
When running in an environment where I can only use LDAP for data collection I am getting an exception when (presumably)  therefore are unable to finish the scan. Is there a way to skip this one test or to otherwise get some of the results that are collected until this point? I have a default auditor licence and tried the last and previous versions all with the same result. 

Any help would be appreciated, thanks!

As follows are the last lines of the trace file, I tried to anonymize all domain information. Sorry that some error messages are in German language:

[...]
[10:57:22] Running ldap enumeration
BaseObject=OneLevel
Filter=(name=ms-*-AdmPwd)
[10:57:22]Calling FindAll
[10:57:23]Enumeration successful
[10:57:23] - Searching for critical and infrastructure objects
[10:57:23] Running ldap enumeration
BaseObject=OneLevel
Filter=(&(objectClass=group)(description=DNS Administrators Group))
[10:57:23]Calling FindAll
Exception: Das angegebene Verzeichnisdienstattribut bzw. der angegebene Verzeichnisdienstwert ist nicht vorhanden.

StackTrace:    bei System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   bei System.DirectoryServices.DirectoryEntry.Bind()
   bei System.DirectoryServices.DirectoryEntry.get_AdsObject()
   bei System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   bei PingCastle.ADWS.LDAPConnection.EnumerateInternalWithLDAP(String distinguishedName, String filter, String[] properties, String scope, WorkOnReturnedObjectByADWS callback) in c:\git\PingCastlePublic\ADWS\LDAPConnection.cs:Zeile 85.
   bei PingCastle.ADWS.ADWebService.Enumerate(Action preambleWithReentry, String distinguishedName, String filter, String[] properties, WorkOnReturnedObjectByADWS callback, String scope) in c:\git\PingCastlePublic\ADWS\ADWebService.cs:Zeile 262.
[Red][10:57:23] An exception occured when doing the task: Perform analysis for TESTDOMAIN.FOO
[Red]Note: you can run the program with the switch --log to get more detail
An exception occured when doing the task: Perform analysis for TESTDOMAIN.FOO
[Red]Exception: Das angegebene Verzeichnisdienstattribut bzw. der angegebene Verzeichnisdienstwert ist nicht vorhanden.

Type:System.Runtime.InteropServices.COMException
[Red]   bei System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   bei System.DirectoryServices.DirectoryEntry.Bind()
   bei System.DirectoryServices.DirectoryEntry.get_AdsObject()
   bei System.DirectoryServices.DirectorySearcher.FindAll(Boolean findMoreThanOne)
   bei PingCastle.ADWS.LDAPConnection.EnumerateInternalWithLDAP(String distinguishedName, String filter, String[] properties, String scope, WorkOnReturnedObjectByADWS callback) in c:\git\PingCastlePublic\ADWS\LDAPConnection.cs:Zeile 85.
   bei PingCastle.ADWS.ADWebService.Enumerate(Action preambleWithReentry, String distinguishedName, String filter, String[] properties, WorkOnReturnedObjectByADWS callback, String scope) in c:\git\PingCastlePublic\ADWS\ADWebService.cs:Zeile 273.
   bei PingCastle.Graph.Export.ExportDataFromActiveDirectoryLive.AddDnsAdmins(GraphObjectReference objectReference) in c:\git\PingCastlePublic\Graph\Export\ExportDataFromActiveDirectoryLive.cs:Zeile 110.
   bei PingCastle.Graph.Export.ExportDataFromActiveDirectoryLive.ExportData(List1 UsersToInvestigate) in c:\git\PingCastlePublic\Graph\Export\ExportDataFromActiveDirectoryLive.cs:Zeile 83.
   bei PingCastle.Graph.Reporting.ReportGenerator.PerformAnalyze(HealthcheckData data, ADDomainInfo domainInfo, ADWebService adws, PingCastleAnalyzerParameters parameters) in c:\git\PingCastlePublic\Graph\Reporting\ReportGenerator.cs:Zeile 40.
   bei PingCastle.Healthcheck.HealthcheckAnalyzer.GeneratePrivilegedGroupAndPermissionsData(ADDomainInfo domainInfo, ADWebService adws, PingCastleAnalyzerParameters parameters) in c:\git\PingCastlePublic\Healthcheck\HealthcheckAnalyzer.cs:Zeile 1294.
   bei PingCastle.Healthcheck.HealthcheckAnalyzer.PerformAnalyze(PingCastleAnalyzerParameters parameters) in c:\git\PingCastlePublic\Healthcheck\HealthcheckAnalyzer.cs:Zeile 115.
   bei PingCastle.Tasks.<>c__DisplayClass12`1.<PerformTheAnalysis>b__11() in c:\git\PingCastlePublic\Tasks.cs:Zeile 406.
   bei PingCastle.Tasks.StartTask(String taskname, TaskDelegate taskdelegate) in c:\git\PingCastlePublic\Tasks.cs:Zeile 830.

**Comment by vletoux** [comment]
Can you contact the support at support@pingcastle.com and attach the full log ?
I'd like also to get the OS version of the DC checked

(without knowing the attribute queried, it will be hard to scope the problem)

**Comment by foobarmuh** [comment]
This seemed to be caused by a really strange setup and not by PingCastle. Thanks for the extremely fast reply time and further help (via mail)!

**Comment by vletoux** [comment]
Was that a Samba AD? I did receive a similar support request

**Comment by foobarmuh** [comment]
Unfortunately, I cannot say for certain as I was only able to get access to the network for a single day. I would think it was a Windows AD but I was not able to get any useful information via LDAP manually either so I ignored it and focussed on the stuff I could reach at the time, sorry.
