### ISSUE TITLE
SHA1 Intermediate Certificates

### ISSUE THREAD

**Issue by bajinabass** [vletoux/pingcastle#8]
Hello, I wanted to say I love this program.  I ran a scan and it's reporting that I have an Intermediate  certificate using SHA1.  It was found in GPO NTLMStore.  I have looked everywhere on all of my servers and I cannot find it.  I am hoping you can explain what/where the GPO NTLMStore is.  Or am I getting a false positive?

**Comment by vletoux** [comment]
It is store on the AD itself and accessible via LDAP
See below the exact LDAP query used for that:
https://github.com/vletoux/pingcastle/blob/7b63f846076baa96147df04b135dd31eef8f5fac/Healthcheck/HealthcheckAnalyzer.cs#L1857
Please note that certutil can be used to display this information

**Comment by bajinabass** [comment]
Thank you!!!   That was driving me nuts!
