### ISSUE TITLE
GPO access denied in v2.9.2.0 when passing creds with user argument

### ISSUE THREAD

**Issue by tmatthews-wr** [vletoux/pingcastle#80]
v2.9.2.0 showing access denied during Gathering GPO Data phase when passing DA member creds via --user argument. Same process on v2.9.1.0 did not display access denied.
Using v2.9.2.0 and windows right-click > Run As with same DA member creds gives no access denied.
Excellent product still. Thanks for creating :)

**Comment by vletoux** [comment]
can you contact us at support@pingcastle.com for further diagnostic and test versions ?
vincent

**Comment by vletoux** [comment]
solved in 2.9.3
