### ISSUE TITLE
LinuxFileStream appears to leak memory in `Read()` method

### ISSUE THREAD

**Issue by JohnLaTwC** [vletoux/pingcastle#85]
## LinuxFileStream appears to leak memory in `Read()` method

Callers using LinuxFileStream declare a buffer to hold the contents read by this function.  The `mem` buffer that is temporarily used is never deallocated.

```diff
    internal class LinuxFileStream : Stream
    {
        int descriptor;
        public LinuxFileStream(int fd) : base()
        {
            descriptor = fd;
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            IntPtr mem = Marshal.AllocHGlobal(count);
            var result = smbc_read(descriptor, mem, count);
            Marshal.Copy(mem, buffer, offset, count);
+           Marshal.FreeHGlobal(mem);
            return result;

        }
```
https://github.com/vletoux/pingcastle/blob/c99d964ce6a0df573c54ff586585140bd5f602ec/ADWS/LinuxFileConnection.cs#L481

**Comment by vletoux** [comment]
Thanks John
(we've meet in real life at BlueHat IL)
The linux part of PingCastle is "work in progress" so there are no really impact there.
if you try to run it, it'll block because the dll behing the pinvoke calls are missing.
But thanks, I'll add the missing line.
