### ISSUE TITLE
Possible token handle leak on call to LogonUser

### ISSUE THREAD

**Issue by JohnLaTwC** [vletoux/pingcastle#86]
In `WindowsFileConnection.GetWindowsIdentityForUser()` a call to LogonUser is made and the returned token is encapsulated in a `WindowsIdentity` object. 

I am not an expert on this but I see a possible token leak in this code.

The API docs for `WindowsIdentity(IntPtr)` note that `CloseHandle` must be called
(https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.-ctor?view=netframework-4.8#System_Security_Principal_WindowsIdentity__ctor_System_IntPtr_)

> Always release userToken by calling the Windows API CloseHandle function. For more information on calling unmanaged code, see Consuming Unmanaged DLL Functions.

Most code examples I saw on the web use `SafeTokenHandle` to manage the token lifetime.

https://github.com/vletoux/pingcastle/blob/c99d964ce6a0df573c54ff586585140bd5f602ec/ADWS/WindowsFileConnection.cs#L122

```diff
        public static WindowsIdentity GetWindowsIdentityForUser(NetworkCredential credential, string optionalRemoteserver = null)
        {
            IntPtr token = IntPtr.Zero;
            string domain = credential.Domain;
            if (String.IsNullOrEmpty(domain))
                domain = optionalRemoteserver;
            Trace.WriteLine("Preparing to login with login = " + credential.UserName + " domain = " + domain);
            bool isSuccess = LogonUser(credential.UserName, (credential.UserName.Contains("@") ? null : domain), credential.Password, LOGON32_LOGON_NEW_CREDENTIALS, LOGON32_PROVIDER_DEFAULT, ref token);
            if (!isSuccess)
            {
                throw new Win32Exception();
            }
! no call to CloseHandle on token
            return new WindowsIdentity(token);
        }
```

**Comment by vletoux** [comment]
Hi John,

I need to impersonate the token, so a code is later called for impersonation.

The token is released later in the process with an Undo and a Dispose (which then close it)
https://github.com/vletoux/pingcastle/blob/19a3890b214bff7cb66b08c55bb4983ca21c8bd1/ADWS/WindowsFileConnection.cs#L81-L99

Did I miss something ?

**Comment by vletoux** [comment]
ok, you were refering about this:
![image](https://user-images.githubusercontent.com/10632326/124960171-5550d900-e01c-11eb-8042-21909c29ac9f.png)
Just checked the implementation of System.Security.Principal.WindowsIdentity and I'm seeing that there is indeed a duplicate token here.
![image](https://user-images.githubusercontent.com/10632326/124960214-5f72d780-e01c-11eb-89ac-0cffb4e8ceff.png)
I'll implement a safehandle there.
Thanks for the report

**Comment by vletoux** [comment]
fixed.

Here is the new reference implementation:
![image](https://user-images.githubusercontent.com/10632326/124961916-5551d880-e01e-11eb-8e7e-aa2c053572e6.png)

I had to use CloseHandle as WindowsIdentity doesn't support safehandle and safehandle doesn't expose the underlying handle
