### ISSUE TITLE
Potential memory leak because Dispose is not called in RemoteScanner.GetCsvData

### ISSUE THREAD

**Issue by JohnLaTwC** [vletoux/pingcastle#88]
# Issue 1

Potential memory leak because Dispose is not called in RemoteScanner.GetCsvData

`RemoteScanner.GetCsvData`  allocates `UNICODE_STRING` but does not call `Dispose()` on them.

```diff
        protected override string GetCsvData(string computer)
        {
            ...
            var names = new NativeMethods.UNICODE_STRING[RemoteReference.Count + customService.Count];
            try
            {
                int i = 0;
                foreach (var entry in RemoteReference)
                {
                    names[i] = new NativeMethods.UNICODE_STRING();
                    names[i].Initialize("NT Service\\" + entry.Key);
! No call to Dispose in function cleanup to free buffer allocated in UNICODE_STRING.Initialize();
                    i++;
                }
                foreach (var entry in customService)
                {
                    names[i] = new NativeMethods.UNICODE_STRING();
                    names[i].Initialize("NT Service\\" + entry);
! No call to Dispose in function cleanup to free buffer allocated in UNICODE_STRING.Initialize();
                    i++;
                }
                IntPtr ReferencedDomains, Sids;
                ret = NativeMethods.LsaLookupNames(PolicyHandle, names.Length, names, out ReferencedDomains, out Sids);
                if (ret == 0xC0000073) //STATUS_NONE_MAPPED
                {
                    sb.Append(computer);
                    sb.Append("\tNo known service found\tIf you think that the information is incorrect, please contact PingCastle support to add the antivirus in the checked list.");
                    return sb.ToString();
                }
                if (ret != 0 && ret != 0x00000107) // ignore STATUS_SOME_NOT_MAPPED
                {
                    Trace.WriteLine("LsaLookupNames 0x" + ret.ToString("x"));
                    sb.Append(computer);
                    sb.Append("\tUnable to lookup\tPingCastle couldn't translate the SID to the computer. The error was 0x" + ret.ToString("x"));
                    return sb.ToString();
                }
               ...
            finally
            {
                NativeMethods.LsaClose(PolicyHandle);
+ Need to loop through names and Dispose of strings
            }
            return sb.ToString();
        }
```

here:
https://github.com/vletoux/pingcastle/blob/19a3890b214bff7cb66b08c55bb4983ca21c8bd1/Scanners/RemoteScanner.cs#L110
and here:
https://github.com/vletoux/pingcastle/blob/19a3890b214bff7cb66b08c55bb4983ca21c8bd1/Scanners/RemoteScanner.cs#L116

# Issue 2
There is a similar issue in `AntivirusScanner.GetCsvData()`

See these two lines:
https://github.com/vletoux/pingcastle/blob/c99d964ce6a0df573c54ff586585140bd5f602ec/Scanners/AntivirusScanner.cs#L172
https://github.com/vletoux/pingcastle/blob/c99d964ce6a0df573c54ff586585140bd5f602ec/Scanners/AntivirusScanner.cs#L178

Probably should be cleaned up here: https://github.com/vletoux/pingcastle/blob/c99d964ce6a0df573c54ff586585140bd5f602ec/Scanners/AntivirusScanner.cs#L245

# Issue 3
You might want to do a pass through all call sites with `UNICODE_STRING.Initialize()` like:

https://github.com/vletoux/pingcastle/blob/19a3890b214bff7cb66b08c55bb4983ca21c8bd1/Scanners/localAdminsEnumerator.cs#L74

https://github.com/vletoux/pingcastle/blob/19a3890b214bff7cb66b08c55bb4983ca21c8bd1/Scanners/ForeignUsersScanner.cs#L120

https://github.com/vletoux/pingcastle/blob/19a3890b214bff7cb66b08c55bb4983ca21c8bd1/RPC/samr.cs#L298

This call site does correctly call `Dispose()`
```diff
        protected override string GetCsvData(string computer)
        {
            StringBuilder sb = new StringBuilder();
            NativeMethods.UNICODE_STRING us = new NativeMethods.UNICODE_STRING();
            NativeMethods.LSA_OBJECT_ATTRIBUTES loa = new NativeMethods.LSA_OBJECT_ATTRIBUTES();
            us.Initialize(computer);
            IntPtr PolicyHandle = IntPtr.Zero;
            uint ret = NativeMethods.LsaOpenPolicy(ref us, ref loa, 0x00000800, out PolicyHandle);
@@ call to Dispose on UNICODE_STRING @@
            us.Dispose();
```
https://github.com/vletoux/pingcastle/blob/19a3890b214bff7cb66b08c55bb4983ca21c8bd1/Scanners/RemoteScanner.cs#L95

**Comment by vletoux** [comment]
fixed with this commit
![image](https://user-images.githubusercontent.com/10632326/125154839-6143b480-e15c-11eb-8c68-f7b941041f90.png)

following your recommandations
![image](https://user-images.githubusercontent.com/10632326/125154848-6c96e000-e15c-11eb-9c38-43577541076b.png)

Will be pushed on the next update
