### ISSUE TITLE
""unknow argument: --graph

### ISSUE THREAD

**Issue by jlawhon** [vletoux/pingcastle#89]
I tried the `--graph` option but it doesn't seem to be recognized by the last few releases.  Am I trying this incorrectly or has the option been deprecated?

I attempted to run  PingCastle like this:
> pingcastle.exe --server lab.local --healthcheck --graph --no-enum-limit

Resulting in this:
> unknow argument: --graph
> switch:
>   --help              : display this message
>   --interactive
>   ...

Removing the `--graph` option allows `--healthcheck` to work as expected.

`pingcastle.exe --graph` also fails similarly.

Thanks!

**Comment by vletoux** [comment]
the --graph report has been merged in the healthcheck report (the compromise graph section)
