### ISSUE TITLE
Assembly en mode mixte

### ISSUE THREAD

**Issue by whoo** [vletoux/pingcastle#92]
Hi, 
PingCastle don't want to start on freshinstall... with:
L'assembly en mode miste est créé avec la version 'v2.0.50727' du runtime et ne peut être chargé dans le runtime 4.0 sans d'autres informations de configuration.

How can solve this issue.
Tks.

**Comment by vletoux** [comment]
you're missing the .config file next to the .exe file.
PingCastle is compiled with .Net 2, but the .config file allows the exe to run under .Net 4

**Comment by whoo** [comment]
Hi,
thanks for quick answer...  but it still didn't work.
* I assume that I did not use the right cmd.
* <code>PingCastle.exe PingCastle.exe.config </code> ?


Thanks

**Comment by whoo** [comment]
Sorry.... i'm definitevely not a .net|window guy.


![image](https://user-images.githubusercontent.com/1499543/127529504-a8392bc0-0e71-42fb-9859-4a5187165e33.png)

**Comment by vletoux** [comment]
Does the .config file looks like this ?
![image](https://user-images.githubusercontent.com/10632326/127541271-44de8866-dadc-4adb-853b-48aa0195f1e2.png)

**Comment by whoo** [comment]
hi @vletoux ,
It works ... useLegacyV2RuntimeActivationPolicy="true" <  wasn't in the configfile.
Thanks
