### ISSUE TITLE
Does not check if krbtgt is disabled

### ISSUE THREAD

**Issue by ratcode404** [vletoux/pingcastle#94]
krbtgt (Used for Golden ticket attacks)

The account password for the krbtgt account should be rotated twice yearly at a minimum. More frequent password rotations are recommended, with 40 days the current recommendation by ANSSI. Additional rotations based on external events, such as departure of an employee who had privileged network access, are also strongly recommended.

The krbtgt account is not active and disabled in the domain, but still shows the 'krbtgt (Used for Golden ticket attacks)' vuln.

**Comment by vletoux** [comment]
`The KRBTGT account is a local default account that acts as a service account for the Key Distribution Center (KDC) service. This account cannot be deleted, and the account name cannot be changed. The KRBTGT account cannot be enabled in Active Directory.`

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn745899(v=ws.11)

krbtgt is disabled on purpose on the AD

**Comment by ratcode404** [comment]
Thank you very much, I was unaware of that!
