### ISSUE TITLE
Windows 1607 and 1809 LTSB/LTSC displayed as obsolete

### ISSUE THREAD

**Issue by EHRETic** [vletoux/pingcastle#96]
Hello Vincent,

I've noticed that with last PingCastle version, that Windows 1607 or 1809 were mentioned as obsolete.
But Windows 1607/1809 can be LTSB/LTSC (I can't remember if it was a normal build too). There Extendended support end date are 13.10.2026 & 09.01.2029 respectively. I've a siginificant ammount of them in my environement.

Therefore, for LTSB/LTSC versions, we should check for both "OperatingSystem" and "OperatingSystemVersion" attributes combination. You'll get either "Windows 10 Enterprise 2016 LTSB" or "Windows 10 Enterprise LTSC" in "OperatingSystem".

https://docs.microsoft.com/en-us/windows/release-health/release-information

![image](https://user-images.githubusercontent.com/28634810/131962837-be3aeec6-92ee-4552-817a-157f121a03e1.png)

Can you confirm this on your side? 😉

**Comment by vletoux** [comment]
It's already done:
when the OS is LTSC, a flag appears and the end of support date is changed
https://github.com/vletoux/pingcastle/blob/001131f863944d5829aa6b1506fe0f7bb8f62af6/Healthcheck/Rules/HeatlcheckRuleStaledObsoleteW10.cs#L90-L101

**Comment by EHRETic** [comment]
Merci Vincent 😉
