### ISSUE TITLE
maybe NPOSL contradicts FAQ on the site

### ISSUE THREAD

**Issue by AlekseyCherepanov** [vletoux/pingcastle#97]
I saw "Non-Profit" in the name of license and it made me to google about the license.

I found this [explanation](https://opensource.stackexchange.com/questions/5776/why-is-the-non-profit-open-software-license-nposl-osi-approved):
> It's the licensor, not the licensee, that needs to be a non-profit.

FAQ at https://www.pingcastle.com/download/ says:
> Technically the code is licensed under a non profit license. This means you can do anything you want as long as you do not financially benefit from it.

So from a quick look, there is a contradiction between the formal license and author's intentions.

**Comment by vletoux** [comment]
There is no contradiction. The code is licensed under a dual license.
First is about the GitHub source code which requires that users are non profit (thus excluding companies)
The second license is about the private source and the binaires. 
this is that one which relax the free use of the binaries if you are a company and run it under your scope.

**Comment by AlekseyCherepanov** [comment]
> First is about the GitHub source code which requires that users are non profit (thus excluding companies)

This particular statement seems wrong according to the [explanation](https://opensource.stackexchange.com/questions/5776/why-is-the-non-profit-open-software-license-nposl-osi-approved). From the explanation, I think that NPOSL does not require user to be non profit. And the source code on github is under NPOSL. Right? (At least I hope now it is more obvious where my confusion came from.)
