### ISSUE TITLE
Not flag LTSB/LTSC as obsolete OS

### ISSUE THREAD

**Issue by RGAGPB** [vletoux/pingcastle#98]
Hi,
I notice that since the last version, pingcastle marks some of my PCs as having an outdated windows 10 version (1607).
In reality this version is not obsolete when it comes to the Enterprise LTSB/LTSC edition. They are still updated by Microsoft.
So I think Ping Castle should be able to see the difference.
Merci 😄

**Comment by vletoux** [comment]
PingCastle is doing this check about LTSC and adapt the end of support date as consequence.
Be sure to not mess the LTSC with non LTSC

**Comment by RGAGPB** [comment]
I think PingCastle makes the difference between "1809" and "1809 (LTSC)" but not between "1607" and "1607 (LSTB)".
I don't have any 1607 non LTSB, but they are all reported as obsolete.
In my case, 1607 = Windows 10 Enterprise 2016 LTSB.

**Comment by vletoux** [comment]
can you contact support@pingcastle.com so i'll send to you a debug version ?

**Comment by An-dir** [comment]
@RGAGPB did you manage to get a solution that worked for you? I currently try to detect all unsupported versions reliable but it is way more complex than expected. Reading 
Automatically would be possible to get it as Json from https://docs.microsoft.com/api/contentbrowser/search/lifecycles?locale=en-us&$skip=0&$top=30&$filter=((products%2Fany(t%3A%20t%20eq%20%27windows%27)))&$orderby=start%20desc and the following sites (max 30 Entries per Query). Another Source to get the versions and their lifecycle in just one file is https://docs.microsoft.com/de-de/lifecycle/products/export/

To be honest, i don't think it is possible to do a query that lists every obsolete version absolutely correct regarding their lifecycle and supportpolicy ("Fixed" or "Modern"). Some editions also do have different lifecycle, but the edition stored in "OperatingSystem" is dependent on the language used! 
![image](https://user-images.githubusercontent.com/11379014/146204514-82a1b0ed-1b94-4da9-9f0c-935ae1432361.png)

You need some other System that manages your clients and does patching/updates... for you to be safe you are up to date and to be more secure. 

@vletoux i guess PingCastle can just give someone a list of systems that might be forgotten to update but can't be 100percent precise. That should be mentioned in the text a bit more detailed. In your detection rule you have LTSC check and naming, but version 1607 is the last version wich is "LTSB" not "LTSC" and has support. You should validate your check and wording here:
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaledObsoleteW10.cs#L90
https://github.com/vletoux/pingcastle/blob/master/Healthcheck/Rules/HeatlcheckRuleStaledObsoleteW10.cs#L94


If someone has a (PowerShell) script that does some magic to get a reliable list of computers from ADDC with all unsupported OS i would be happy. Using WMI or any other remoting is often blocked in secure environments, so ADDC is the only datasource despite you have SCCM.

My opinion: PingCastle can't win that game, but it can tell you that you might have forgotten something.

**Comment by An-dir** [comment]
I know one solution that is not up to date but looks promising:
https://github.com/GavinTownsend/Audit-Compliance/blob/master/get-AD_OSCompliance.ps1

**Comment by vletoux** [comment]
the bug is already fixed for the next version
But the release is reserved for paid customer.
Next free version end of January
