### ISSUE TITLE
REQUEST: Add CSS file for easy branding

### ISSUE THREAD

**Issue by brolifen** [vletoux/pingcastle#99]
It would be nice if the CSS file for the HTML layout was not part of the code but was externally available for easy branding. The current branding process is not very userfriendly especially when wanting to target specific elements in the layout.

**Comment by vletoux** [comment]
i remind that this feature is reserved for pingcastle customers.
if a css file is present, the whole html file cannot be used as a stand alone file.
If you are a paid customer, you can inject using javacsript a reference to a css file

**Comment by brolifen** [comment]
Hi, Yes I'm a paid customer. The CSS file can be standalone in the folder for easy customization and integrated in the HTML report when generating it.

**Comment by vletoux** [comment]
please contact support@pingcastle.com to continue this conversation
